import { Terminal, Globe, Wifi, Settings, Eye, Server, Router, Network, Book, Zap, Keyboard, LucideIcon, Lightbulb, FileText, Layers, Shield, Radio } from 'lucide-react';

export interface CommandDefinition {
  id: string;
  icon: LucideIcon;
  title: string;
  cmds: [string, string, string?][];
  type?: 'commands' | 'info' | 'examples';
}

export function getCommandCategories(isTR: boolean): CommandDefinition[] {
  return [
    {
      id: 'keyboard_shortcuts',
      icon: Keyboard,
      title: isTR ? 'Fare & Klavye Kısayolları' : 'Mouse & Keyboard Shortcuts',
      type: 'info',
      cmds: [
        ['F1', isTR ? 'Yardım / Kısayollar panelini aç' : 'Open Help / Shortcuts panel'],
        ['F5', isTR ? 'Ağı yenile' : 'Refresh network'],
        ['Escape', isTR ? 'Pencereleri kapat / Seçimi kaldır' : 'Close windows / Clear selection'],
        ['Tab', isTR ? 'Cihazlar arasında gezin' : 'Navigate between devices'],
        ['Shift + Tab', isTR ? 'Görev Yöneticisi (Pencere listesi ve pencereler arası geçiş)' : 'Open Task Switcher and switch between device windows'],
        ['Enter', isTR ? 'Seçili cihaz penceresini aç' : 'Open selected device window'],
        ['Ctrl + M', isTR ? 'Aktif pencereyi simge durumuna küçült / büyüt' : 'Minimize / maximize active device window'],
        ['Alt + M', isTR ? 'Minimap (Harita) göster / gizle' : 'Toggle Minimap display'],
        ['Alt + L', isTR ? 'Ağ Olay Günlüğü panelini aç / kapat' : 'Toggle Network Event Log panel'],
        ['Alt + F', isTR ? 'Tüm cihazları ekrana sığdır (Fit View)' : 'Zoom to fit all devices'],
        ['Ctrl + S', isTR ? 'Projeyi kaydet' : 'Save project'],
        ['Ctrl + O', isTR ? 'Proje aç' : 'Open project'],
        ['Alt + N', isTR ? 'Yeni proje oluştur' : 'Create new project'],
        ['Ctrl + Z', isTR ? 'Geri al (Topoloji & Hizalama Hareketi)' : 'Undo (Undo topology & alignment)'],
        ['Ctrl + Y / Ctrl + Shift + Z', isTR ? 'İleri al (Redo / Yeniden yap)' : 'Redo'],
        ['Ctrl + C', isTR ? 'Seçili cihazı kopyala' : 'Copy selected device'],
        ['Ctrl + X', isTR ? 'Seçili cihazı kes' : 'Cut selected device'],
        ['Ctrl + V', isTR ? 'Yapıştır' : 'Paste'],
        ['Ctrl + A', isTR ? 'Tümünü seç' : 'Select all'],
        ['Delete / Backspace', isTR ? 'Seçili cihazı / öğeyi sil' : 'Delete selected device / item'],
        ['Ctrl + L', isTR ? 'CMD & CLI Ekran geçmişini temizle' : 'Clear CMD & CLI Terminal screen'],
        ['Ctrl + P', isTR ? 'Yazdır / Sertifika' : 'Print / Certificate'],
        ['S', isTR ? 'Simülasyon modunu aç/kapat' : 'Toggle simulation mode'],
        ['P', isTR ? 'Paket analizi: Oynat / Duraklat' : 'Packet analysis: Play / Pause'],
        ['N', isTR ? 'Paket analizi: Sonraki Hop (duraklatıldığında)' : 'Packet analysis: Next Hop (when paused)'],
        ['"', isTR ? 'Timeline panelini aç/kapat' : 'Toggle timeline panel'],
        ['Sol Tık (Cihaz)', isTR ? 'Cihazı seç veya sürükle' : 'Select or drag device'],
        ['Çift Tık (Cihaz)', isTR ? 'Cihaz kontrol / yapılandırma penceresini aç' : 'Open device config / control window'],
        ['Sağ Tık (Cihaz / Tuval)', isTR ? 'Bağlam menüsünü (Context Menu) aç' : 'Open context menu'],
        ['Fare Tekerleği (Scroll) / Ctrl + Scroll', isTR ? 'Tuval üzerinde yakınlaştır / uzaklaştır (Zoom In / Out)' : 'Zoom canvas in / out'],
        ['Sol Tık + Sürükle / Space + Sürükle', isTR ? 'Tuvali (Canvas) kaydır' : 'Pan canvas'],
        ['Fare Orta Tuşu + Sürükle', isTR ? 'Çoklu seçim kutusu oluştur (Çoklu Cihaz Seçimi)' : 'Box multi-selection (Multi-select devices)'],
        ['Shift + Fare Orta Tuşu / Sol Tık', isTR ? 'Mevcut seçime cihaz ekle / çıkar' : 'Add / remove device from selection'],
        ['Metin Seçimi (Mouse Selection)', isTR ? 'CMD, CLI & Konsol geçmişinden metin seçince OTOMATİK KOPYALA' : 'Auto-Copy text selection from CMD, CLI & Console outputs'],
        ['Side-by-Side (Böl)', isTR ? 'Açık pencereleri ekranda yan yana bölünmüş yerleştir' : 'Arrange open windows side-by-side (Split View)'],
        ['Tabbed View (Sekme)', isTR ? 'Açık pencereleri sekme moduna dönüştür' : 'Switch open windows to tabbed layout mode'],
      ]
    },
    {
      id: 'command_modes',
      icon: Layers,
      title: isTR ? 'Komut Modları' : 'Command Modes',
      type: 'commands',
      cmds: [
        ['Router>', isTR ? 'Kullanıcı Modu' : 'User Mode'],
        ['Router#', isTR ? 'Ayrıcalıklı Mod' : 'Privileged Mode'],
        ['(config)#', isTR ? 'Global Yapılandırma' : 'Global Config'],
        ['(config-if)#', isTR ? 'Arayüz Yapılandırma' : 'Interface Config'],
      ]
    },
    {
      id: 'subnetting_info',
      icon: Network,
      title: isTR ? 'Subnetting & Alt Ağlar' : 'Subnetting & Subnets',
      type: 'info',
      cmds: [
        [isTR ? 'Subnet Mask (Alt Ağ Maskesi)' : 'Subnet Mask', isTR ? 'IP adresinin ağ ve host bölümlerini ayırmak için kullanılır (ör: /24 = 255.255.255.0 = 256 adres).' : 'Used to separate network and host portions of IP address (e.g. /24 = 255.255.255.0 = 256 addresses).'],
        [isTR ? 'Ağ Adresi (Network Address)' : 'Network Address', isTR ? 'Alt ağın ilk adresidir, cihazlara atanamaz (ör: 192.168.1.0).' : 'First address of the subnet, cannot be assigned to devices (e.g. 192.168.1.0).'],
        [isTR ? 'Yayın Adresi (Broadcast Address)' : 'Broadcast Address', isTR ? 'Alt ağın son adresidir, tüm cihazlara yayın için kullanılır (ör: 192.168.1.255).' : 'Last address of the subnet, used to broadcast to all devices (e.g. 192.168.1.255).'],
        [isTR ? 'Kullanılabilir Host Sayısı' : 'Usable Host Count', isTR ? '2^(32 - Prefix) - 2 formülü ile hesaplanır.' : 'Calculated using 2^(32 - Prefix) - 2 formula.'],
      ]
    },
    {
      id: 'system',
      icon: Terminal,
      title: isTR ? 'Oturum' : 'Session',
      type: 'commands',
      cmds: [
        ['enable', isTR ? 'Ayrıcalıklı moda geç' : 'Enter privileged mode', '>'],
        ['disable', isTR ? 'Kullanıcı moduna dön' : 'Return to user mode', '#'],
        ['configure terminal', isTR ? 'Yapılandırma modu' : 'Enter config mode', '#'],
        ['exit', isTR ? 'Moddan çık' : 'Exit current mode'],
        ['end', isTR ? 'Ayrıcalıklı moda dön' : 'Return to privileged mode'],
        ['help', isTR ? 'Yardım sistemini göster' : 'Display help system'],
      ]
    },
    {
      id: 'linux_commands',
      icon: Terminal,
      title: isTR ? 'Linux Terminal Komutları' : 'Linux Terminal Commands',
      type: 'commands',
      cmds: [
        ['ls [-l] [-la]', isTR ? 'Dizin içeriğini listele (ls -l: detaylı, ls -la: gizli dosyalar)' : 'List directory contents (ls -l: long, ls -la: hidden)'],
        ['pwd', isTR ? 'Mevcut çalışma dizinini göster' : 'Print working directory'],
        ['cd <dizin>', isTR ? 'Dizin değiştir (cd .. bir üst dizin, cd ~ ev dizini)' : 'Change directory (cd .., cd ~)'],
        ['cat <dosya>', isTR ? 'Dosya içeriğini görüntüle' : 'View file content'],
        ['touch <dosya>', isTR ? 'Boş dosya oluştur' : 'Create an empty file'],
        ['mkdir <dizin>', isTR ? 'Yeni klasör/dizin oluştur' : 'Create a new directory'],
        ['rm <dosya>', isTR ? 'Dosya veya klasör sil' : 'Remove file or directory'],
        ['cp <kaynak> <hedef>', isTR ? 'Dosya kopyala' : 'Copy file'],
        ['mv <kaynak> <hedef>', isTR ? 'Dosyayı taşı veya yeniden adlandır' : 'Move or rename file'],
        ['echo "metin" > <dosya>', isTR ? 'Ekrana yazdır veya dosyaya yaz/ekle (>>)' : 'Print text or write/append (>>) to file'],
        ['ifconfig / ip addr', isTR ? 'Ağ arayüzlerini ve IP adreslerini listele' : 'Display network interfaces & IP addresses'],
        ['dhclient eth0', isTR ? 'Linux DHCP adres kiralamasını yenile' : 'Renew the Linux DHCP lease'],
        ['dhclient -r eth0', isTR ? 'Linux DHCP adres kiralamasını bırak' : 'Release the Linux DHCP lease'],
        ['ip route', isTR ? 'Yönlendirme tablosunu görüntüle' : 'Show IP routing table'],
        ['ping <ip/host>', isTR ? 'ICMP ağ bağlantısı testi' : 'Test network connectivity (ICMP)'],
        ['traceroute <ip/host>', isTR ? 'Hedefe giden paket rotasını izle' : 'Trace route to target'],
        ['nslookup <domain>', isTR ? 'DNS sorgulama (alan adı IP karşılığı)' : 'Perform DNS lookup'],
        ['netstat / arp', isTR ? 'Ağ bağlantıları ve ARP tablosu' : 'Network status & ARP table'],
        ['whoami / hostname', isTR ? 'Kullanıcı adı ve bilgisayar adını göster' : 'Print username and system hostname'],
        ['uname -a', isTR ? 'Linux çekirdek ve sistem detaylarını göster' : 'Display Linux kernel and OS details'],
        ['date / uptime', isTR ? 'Sistem saati ve çalışma süresini göster' : 'Display date and system uptime'],
        ['python3 <script.py>', isTR ? 'Python betiği çalıştır' : 'Run Python script'],
        ['clear', isTR ? 'Terminal ekranını temizle' : 'Clear terminal screen'],
        ['help', isTR ? 'Linux dahili komut kılavuzunu göster' : 'Display internal Linux help'],
      ]
    },
    {
      id: 'privileged',
      icon: Server,
      title: isTR ? 'Privileged EXEC' : 'Privileged EXEC',
      type: 'commands',
      cmds: [
        ['ping <host> [s] [c]', isTR ? 'Bağlantı testi (ICMP)' : 'Ping host (ICMP)', '#'],
        ['traceroute <host>', isTR ? 'Rota izleme' : 'Trace route', '#'],
        ['clock set <hh:mm:ss> <day> <month> <year>', isTR ? 'Sistem saatini ayarla' : 'Set system clock', '#'],
        ['telnet <host> [port]', isTR ? 'Telnet bağlantısı' : 'Telnet connection', '#'],
        ['ssh [-l user] <host>', isTR ? 'SSH bağlantısı' : 'SSH connection', '#'],
        ['write memory', isTR ? 'Yapılandırmayı kaydet' : 'Save configuration', '#'],
        ['copy running-config startup-config', isTR ? 'Yapılandırmayı kaydet' : 'Save config', '#'],
        ['copy running-config flash:', isTR ? 'Flash\'a kaydet' : 'Save to flash', '#'],
        ['copy flash: startup-config', isTR ? 'Flash\'tan geri yükle' : 'Restore from flash', '#'],
        ['delete flash:vlan.dat', isTR ? 'VLAN veritabanı sil' : 'Delete VLAN database', '#'],
        ['erase startup-config', isTR ? 'Startup config sil' : 'Erase startup config', '#'],
        ['erase nvram', isTR ? 'NVRAM dosya sistemini sil' : 'Erase NVRAM', '#'],
        ['reload', isTR ? 'Cihazı yeniden yükle' : 'Reload device', '#'],
        ['ip route <n> <mask> <h>', isTR ? 'Statik rota ekle' : 'Add static route', '#'],
        ['no ip route <n> <mask> <h>', isTR ? 'Statik rotayı sil' : 'Remove static route', '#'],
        ['debug <type>', isTR ? 'Hata ayıklamayı aç' : 'Enable debugging', '#'],
        ['undebug all', isTR ? 'Tüm hataları kapat' : 'Disable all debugging', '#'],
        ['terminal length <0-512>', isTR ? 'Terminal satır uzunluğu' : 'Set terminal length', '#'],
        ['clear arp-cache', isTR ? 'ARP önbelleğini sil' : 'Clear ARP cache', '#'],
        ['clear mac address-table', isTR ? 'MAC tablosunu sil' : 'Clear MAC table', '#'],
        ['clear counters', isTR ? 'Sayaçları sıfırla' : 'Clear counters', '#'],
        ['do <command>', isTR ? 'Ayrıcalıklı komut çalıştır' : 'Execute privileged command', '(config)#'],
        ['more <file>', isTR ? 'Dosya içeriğini göster' : 'Display file contents', '#'],
        ['setup', isTR ? 'Kurulum sihirbazı' : 'Setup wizard', '#'],
        ['test', isTR ? 'Tanılama testi' : 'Diagnostic test', '#'],
        ['disconnect <session>', isTR ? 'Oturumu kes' : 'Disconnect session', '#'],
        ['resume <session>', isTR ? 'Oturuma devam et' : 'Resume session', '#'],
        ['suspend', isTR ? 'Oturumu askıya al' : 'Suspend session', '#'],
        ['copy running-config tftp:', isTR ? 'TFTP\'ye yapılandırma gönder' : 'Copy config to TFTP', '#'],
        ['copy tftp: running-config', isTR ? 'TFTP\'den yapılandırma al' : 'Restore config from TFTP', '#'],
        ['copy startup-config running-config', isTR ? 'Startup config\'u çalıştır' : 'Merge startup to running', '#'],
        ['copy tftp: flash:', isTR ? 'TFTP\'den nOS yükle' : 'Copy nOS from TFTP', '#'],
        ['clear line <n>', isTR ? 'Hattı sıfırla' : 'Clear line', '#'],
        ['clear interface <type/n>', isTR ? 'Arayüz sayaçlarını sıfırla' : 'Clear interface counters', '#'],
        ['terminal monitor', isTR ? 'Log mesajlarını görüntüle' : 'Monitor log messages', '#'],
        ['terminal no monitor', isTR ? 'Log görüntülemeyi kapat' : 'Stop monitoring logs', '#'],
        ['terminal width <n>', isTR ? 'Terminal genişliği' : 'Set terminal width', '#'],
      ]
    },
    {
      id: 'global',
      icon: Globe,
      title: isTR ? 'Global Yapılandırma' : 'Global Config',
      type: 'commands',
      cmds: [
        ['hostname <name>', isTR ? 'Cihaz adı' : 'Set hostname', '(config)#'],
        ['vlan <id>', isTR ? 'VLAN oluştur' : 'Create VLAN', '(config)#'],
        ['no vlan <id>', isTR ? 'VLAN sil' : 'Delete VLAN', '(config)#'],
        ['name <name>', isTR ? 'VLAN adı (vlan modunda)' : 'Set VLAN name', '(config-vlan)#'],
        ['interface <name>', isTR ? 'Arayüz seç' : 'Select interface', '(config)#'],
        ['interface range <r>', isTR ? 'Arayüz aralığı' : 'Interface range', '(config)#'],
        ['no interface vlan <id>', isTR ? 'VLAN arayüzünü sil' : 'Delete VLAN interface', '(config)#'],
        ['ip routing', isTR ? 'IP yönlendirme (L3)' : 'Enable IP routing (L3)', '(config)#'],
        ['no ip routing', isTR ? 'IP yönlendirmeyi kapat' : 'Disable IP routing', '(config)#'],
        ['ip default-gateway <ip>', isTR ? 'Varsayılan ağ geçidi' : 'Set default gateway', '(config)#'],
        ['ip domain-name <name>', isTR ? 'Alan adı' : 'Set domain name', '(config)#'],
        ['no ip domain lookup', isTR ? 'DNS aramayı kapat' : 'Disable DNS lookup', '(config)#'],
        ['ip http server', isTR ? 'HTTP sunucusunu aç' : 'Enable HTTP server', '(config)#'],
        ['no ip http server', isTR ? 'HTTP sunucusunu kapat' : 'Disable HTTP server', '(config)#'],
        ['ip ssh version {1|2}', isTR ? 'SSH versiyonu' : 'Set SSH version', '(config)#'],
        ['ip ssh time-out <s>', isTR ? 'SSH zaman aşımı' : 'Set SSH timeout', '(config)#'],
        ['ip ssh authentication-retries <n>', isTR ? 'SSH deneme sayısı' : 'SSH retry limit', '(config)#'],
        ['ip dhcp snooping', isTR ? 'DHCP snooping aç' : 'Enable DHCP snooping', '(config)#'],
        ['ip dhcp snooping vlan <ids>', isTR ? 'VLANlarda DHCP snooping' : 'DHCP snooping on VLANs', '(config)#'],
        ['service password-enc', isTR ? 'Parolaları şifrele' : 'Encrypt passwords', '(config)#'],
        ['enable secret <pass>', isTR ? 'Enable secret parolası' : 'Set enable secret', '(config)#'],
        ['enable password <pass>', isTR ? 'Enable password parolası' : 'Set enable password', '(config)#'],
        ['banner motd #<msg>#', isTR ? 'MOTD banner' : 'MOTD banner', '(config)#'],
        ['banner login #<msg>#', isTR ? 'Login banner' : 'Login banner', '(config)#'],
        ['no banner {motd|login}', isTR ? 'Banner sil' : 'Remove banner', '(config)#'],
        ['vtp mode {server|client}', isTR ? 'VTP modu' : 'Set VTP mode', '(config)#'],
        ['vtp domain <name>', isTR ? 'VTP etki alanı' : 'Set VTP domain', '(config)#'],
        ['vtp password <pass>', isTR ? 'VTP parolası' : 'Set VTP password', '(config)#'],
        ['spanning-tree mode {m}', isTR ? 'STP modu' : 'Set STP mode', '(config)#'],
        ['spanning-tree vlan <id> priority <val>', isTR ? 'VLAN STP önceliği' : 'VLAN STP priority', '(config)#'],
        ['spanning-tree vlan <id> root', isTR ? 'VLAN STP root' : 'VLAN STP root', '(config)#'],
        ['no spanning-tree', isTR ? 'STP\'yi kapat' : 'Disable spanning-tree', '(config)#'],
        ['username <n> pass <p>', isTR ? 'Kullanıcı oluştur' : 'Create user', '(config)#'],
        ['no username <name>', isTR ? 'Kullanıcıyı sil' : 'Remove user', '(config)#'],
        ['cdp run', isTR ? 'CDP\'yi aç' : 'Enable CDP globally', '(config)#'],
        ['mls qos', isTR ? 'QoS\'u aç' : 'Enable MLS QoS', '(config)#'],
        ['ip dhcp pool <name>', isTR ? 'DHCP havuzu' : 'Create DHCP pool', '(config)#'],
        ['no ip dhcp pool <name>', isTR ? 'DHCP havuzunu sil' : 'Remove DHCP pool', '(config)#'],
        ['ip dhcp excluded <ip>', isTR ? 'DHCP hariç tut' : 'Exclude DHCP addr', '(config)#'],
        ['ip nat pool <n> <s-e> <m>', isTR ? 'NAT havuzu tanımla' : 'Define NAT pool', '(config)#'],
        ['ip nat inside source <rule>', isTR ? 'NAT kuralı ekle' : 'Add NAT rule', '(config)#'],
        ['ntp server <ip>', isTR ? 'NTP sunucusu' : 'Set NTP server', '(config)#'],
        ['clock timezone <n> <o>', isTR ? 'Zaman dilimi' : 'Set timezone', '(config)#'],
        ['ip name-server <ip>', isTR ? 'DNS sunucusu' : 'Set DNS server', '(config)#'],
        ['system mtu <size>', isTR ? 'Sistem MTU' : 'Set system MTU', '(config)#'],
        ['errdisable recovery', isTR ? 'Hata kurtarma' : 'Errdisable recovery', '(config)#'],
        ['spanning-tree portfast default', isTR ? 'Global PortFast' : 'Global PortFast', '(config)#'],
        ['ipv6 unicast-routing', isTR ? 'IPv6 yönlendirme' : 'Enable IPv6 routing', '(config)#'],
        ['crypto key generate rsa', isTR ? 'RSA anahtarı üret (SSH)' : 'Generate RSA keys', '(config)#'],
        ['crypto isakmp policy <pri>', isTR ? 'ISAKMP politikası oluştur' : 'Create ISAKMP policy', '(config)#'],
        ['crypto isakmp key <secret> address <peer>', isTR ? 'ISAKMP pre-share anahtarı tanımla' : 'Define ISAKMP pre-shared key', '(config)#'],
        ['crypto ipsec transform-set <name> <encr> <auth>', isTR ? 'IPsec dönüştürme kümesi' : 'Define IPsec transform set', '(config)#'],
        ['crypto map <name> <seq> ipsec-isakmp', isTR ? 'Crypto Map haritası oluştur' : 'Create Crypto Map', '(config)#'],
        ['ip dhcp snooping information option', isTR ? 'DHCP Snooping Option 82 bilgi eklemeyi aç' : 'Enable DHCP Snooping Option 82', '(config)#'],
        ['snmp-server community <c>', isTR ? 'SNMP topluluğu' : 'Set SNMP community', '(config)#'],
        ['archive', isTR ? 'Arşiv yapılandırması' : 'Archive configuration', '(config)#'],
        ['ip prefix-list <name> [seq <n>] {permit|deny} <prefix> [ge <ge>] [le <le>]', isTR ? 'IP Prefix List kuralı tanımla' : 'Define IP prefix list rule', '(config)#'],
        ['ipv6 prefix-list <name> [seq <n>] {permit|deny} <prefix> [ge <ge>] [le <le>]', isTR ? 'IPv6 Prefix List kuralı tanımla' : 'Define IPv6 prefix list rule', '(config)#'],
        ['route-map <name> {permit|deny} [<seq>]', isTR ? 'Route-Map politikası oluştur' : 'Create Route-Map policy', '(config)#'],
        ['ip flow-export destination <ip> <port>', isTR ? 'NetFlow dışa aktarım hedefi' : 'Set NetFlow export destination', '(config)#'],
        ['ip flow-export version {5|9}', isTR ? 'NetFlow sürümü' : 'Set NetFlow export version', '(config)#'],
        ['spanning-tree loopguard default', isTR ? 'Global STP Loop Guard aç' : 'Enable global STP Loop Guard', '(config)#'],
        ['ipv6 router eigrp <as>', isTR ? 'IPv6 EIGRP yönlendirme süreci' : 'Enable IPv6 EIGRP process', '(config)#'],
        ['ip arp inspection vlan <id>', isTR ? 'DAI (ARP Denetimi)' : 'Enable DAI on VLAN', '(config)#'],
      ]
    },

    {
      id: 'examples-dhcp',
      icon: Lightbulb,
      title: isTR ? 'Örnek: DHCP Sunucusu' : 'Example: DHCP Server',
      type: 'examples',
      cmds: [
        ['ip dhcp pool MY_POOL', isTR ? '1. DHCP havuzu oluştur' : '1. Create DHCP pool', '(config)#'],
        ['network 192.168.1.0 255.255.255.0', isTR ? '2. Havuz ağını ve maskesini belirle' : '2. Define pool network and mask', '(config-dhcp)#'],
        ['default-router 192.168.1.1', isTR ? '3. Varsayılan ağ geçidini belirle' : '3. Set default gateway', '(config-dhcp)#'],
        ['dns-server 8.8.8.8', isTR ? '4. DNS sunucusunu belirle' : '4. Set DNS server', '(config-dhcp)#'],
        ['exit', isTR ? '5. Havuz modundan çık' : '5. Exit pool mode', '(config-dhcp)#'],
        ['ip dhcp excluded-address 192.168.1.1', isTR ? '6. Dağıtılmayacak adresleri hariç tut' : '6. Exclude addresses from pool', '(config)#'],
      ]
    },
    {
      id: 'examples-wifi',
      icon: Wifi,
      title: isTR ? 'Örnek: Wi-Fi Ayarları' : 'Example: Wi-Fi Setup',
      type: 'examples',
      cmds: [
        ['dot11 ssid MY_WIFI', isTR ? '1. SSID yapılandırmasına gir' : '1. Enter SSID config', '(config)#'],
        ['authentication open', isTR ? '2. Açık kimlik doğrulama (veya WPA)' : '2. Open authentication (or WPA)', '(config-ssid)#'],
        ['guest-mode', isTR ? '3. SSID\'yi yayınla (Beacon)' : '3. Broadcast SSID (Beacon)', '(config-ssid)#'],
        ['exit', isTR ? '4. SSID modundan çık' : '4. Exit SSID mode', '(config-ssid)#'],
        ['interface Dot11Radio 0', isTR ? '5. Radyo arayüzüne gir' : '5. Enter radio interface', '(config)#'],
        ['ssid MY_WIFI', isTR ? '6. SSID\'yi radyoya ata' : '6. Assign SSID to radio', '(config-if)#'],
        ['no shutdown', isTR ? '7. Radyoyu etkinleştir' : '7. Enable radio', '(config-if)#'],
      ]
    },
    {
      id: 'examples-ssh',
      icon: Server,
      title: isTR ? 'Örnek: SSH Sunucusu' : 'Example: SSH Server',
      type: 'examples',
      cmds: [
        ['hostname R1', isTR ? '1. Cihaz adını belirle' : '1. Set the device hostname', '(config)#'],
        ['ip domain-name example.local', isTR ? '2. RSA anahtarı için alan adı belirle' : '2. Set the domain name for RSA key generation', '(config)#'],
        ['username admin privilege 15 secret netsim', isTR ? '3. Yerel yönetici kullanıcısı oluştur' : '3. Create a local administrator account', '(config)#'],
        ['crypto key generate rsa', isTR ? '4. RSA anahtarlarını oluştur' : '4. Generate RSA keys', '(config)#'],
        ['ip ssh version 2', isTR ? '5. SSH sürüm 2’yi etkinleştir' : '5. Enable SSH version 2', '(config)#'],
        ['line vty 0 4', isTR ? '6. VTY hatlarını yapılandır' : '6. Configure the VTY lines', '(config)#'],
        ['login local', isTR ? '7. Yerel kullanıcı doğrulamasını etkinleştir' : '7. Enable local user authentication', '(config-line)#'],
        ['transport input ssh', isTR ? '8. Yalnızca SSH erişimine izin ver' : '8. Allow SSH access only', '(config-line)#'],
        ['ssh -l admin 192.168.1.150', isTR ? '9. SSH bağlantısını test et' : '9. Test the SSH connection', '>'],
      ]
    },
    {
      id: 'examples-vlan',
      icon: Layers,
      title: isTR ? 'Örnek: VLAN & Trunk' : 'Example: VLAN & Trunk',
      type: 'examples',
      cmds: [
        ['vlan 10', isTR ? '1. VLAN 10 oluştur' : '1. Create VLAN 10', '(config)#'],
        ['name SALES', isTR ? '2. VLAN adını "SALES" yap' : '2. Name VLAN "SALES"', '(config-vlan)#'],
        ['interface range fa0/1 - 10', isTR ? '3. İlk 10 portu seç' : '3. Select first 10 ports', '(config)#'],
        ['switchport mode access', isTR ? '4. Portları erişim moduna al' : '4. Set ports to access mode', '(config-if)#'],
        ['switchport access vlan 10', isTR ? '5. Portları VLAN 10\'a ata' : '5. Assign ports to VLAN 10', '(config-if)#'],
        ['interface gi0/1', isTR ? '6. Uplink portunu seç' : '6. Select uplink port', '(config)#'],
        ['switchport mode trunk', isTR ? '7. Portu Trunk moduna al' : '7. Set port to Trunk mode', '(config-if)#'],
      ]
    },
    {
      id: 'examples-nat',
      icon: Globe,
      title: isTR ? 'Örnek: NAT & PAT' : 'Example: NAT & PAT',
      type: 'examples',
      cmds: [
        ['access-list 1 permit 192.168.1.0 0.0.0.255', isTR ? '1. İç ağ için ACL tanımla' : '1. Define ACL for internal network', '(config)#'],
        ['ip nat inside source list 1 interface gi0/0 overload', isTR ? '2. PAT (Overload) kuralı ekle' : '2. Add PAT (Overload) rule', '(config)#'],
        ['interface gi0/1', isTR ? '3. İç arayüze gir' : '3. Select inside interface', '(config)#'],
        ['ip nat inside', isTR ? '4. İç arayüz olarak işaretle' : '4. Mark as inside interface', '(config-if)#'],
        ['interface gi0/0', isTR ? '5. Dış (internet) arayüzüne gir' : '5. Select outside interface', '(config)#'],
        ['ip nat outside', isTR ? '6. Dış arayüz olarak işaretle' : '6. Mark as outside interface', '(config-if)#'],
        ['show ip nat translations', isTR ? '7. NAT çeviri tablosunu gör' : '7. View NAT translations', '#'],
      ]
    },
    {
      id: 'examples-router-on-a-stick',
      icon: Router,
      title: isTR ? 'Örnek: Router-on-a-Stick' : 'Example: Router-on-a-Stick',
      type: 'examples',
      cmds: [
        ['interface gi0/0.10', isTR ? '1. VLAN 10 alt-arayüzünü oluştur' : '1. Create VLAN 10 subinterface', '(config)#'],
        ['encapsulation dot1q 10', isTR ? '2. Dot1Q kapsülleme & VLAN 10 ataması' : '2. Set Dot1Q encapsulation & VLAN 10', '(config-subif)#'],
        ['ip address 192.168.10.1 255.255.255.0', isTR ? '3. VLAN 10 ağ geçidi IP\'sini ata' : '3. Set VLAN 10 gateway IP', '(config-subif)#'],
        ['interface gi0/0.20', isTR ? '4. VLAN 20 alt-arayüzünü oluştur' : '4. Create VLAN 20 subinterface', '(config)#'],
        ['encapsulation dot1q 20', isTR ? '5. Dot1Q kapsülleme & VLAN 20 ataması' : '5. Set Dot1Q encapsulation & VLAN 20', '(config-subif)#'],
        ['ip address 192.168.20.1 255.255.255.0', isTR ? '6. VLAN 20 ağ geçidi IP\'sini ata' : '6. Set VLAN 20 gateway IP', '(config-subif)#'],
        ['interface gi0/0', isTR ? '7. Ana fiziksel arayüze gir ve aç' : '7. Enter main physical interface & enable', '(config)#'],
        ['no shutdown', isTR ? '8. Fiziksel arayüzü etkinleştir' : '8. Enable physical interface', '(config-if)#'],
      ]
    },
    {
      id: 'examples-etherchannel',
      icon: Layers,
      title: isTR ? 'Örnek: EtherChannel (LACP)' : 'Example: EtherChannel (LACP)',
      type: 'examples',
      cmds: [
        ['interface range fa0/1 - 2', isTR ? '1. Bağlanacak fiziksel portları seç' : '1. Select physical ports to bundle', '(config)#'],
        ['channel-group 1 mode active', isTR ? '2. LACP active modunda grupla' : '2. Group in LACP active mode', '(config-if-range)#'],
        ['interface port-channel 1', isTR ? '3. Oluşan Port-Channel arayüzüne gir' : '3. Select created Port-Channel interface', '(config)#'],
        ['switchport mode trunk', isTR ? '4. Mantıksal portu Trunk yap' : '4. Set logical port to Trunk mode', '(config-if)#'],
        ['show etherchannel summary', isTR ? '5. Gruba dahil durumunu kontrol et' : '5. Verify EtherChannel summary status', '#'],
      ]
    },
    {
      id: 'examples-hsrp',
      icon: Server,
      title: isTR ? 'Örnek: HSRP Ağ Geçidi Yedekleme' : 'Example: HSRP Gateway Redundancy',
      type: 'examples',
      cmds: [
        ['interface gi0/0', isTR ? '1. LAN tarafındaki arayüze gir' : '1. Enter LAN-facing interface', '(config)#'],
        ['standby 1 ip 192.168.1.254', isTR ? '2. Sanal IP (Virtual IP) adresini ata' : '2. Set Virtual IP address', '(config-if)#'],
        ['standby 1 priority 110', isTR ? '3. Önceliği artır (Birincil Router yap)' : '3. Increase priority (Make Active Router)', '(config-if)#'],
        ['standby 1 preempt', isTR ? '4. Geri devralma (preempt) modunu aç' : '4. Enable preemption mode', '(config-if)#'],
        ['show standby brief', isTR ? '5. HSRP aktif/beklemede durumunu kontrol et' : '5. Verify HSRP status', '#'],
      ]
    },
    {
      id: 'examples-ospf',
      icon: Network,
      title: isTR ? 'Örnek: OSPF Yönlendirme' : 'Example: OSPF Routing',
      type: 'examples',
      cmds: [
        ['router ospf 1', isTR ? '1. OSPF sürecini başlat (Process ID 1)' : '1. Enable OSPF process 1', '(config)#'],
        ['router-id 1.1.1.1', isTR ? '2. Router ID kimliğini belirle' : '2. Set Router ID', '(config-router)#'],
        ['network 192.168.1.0 0.0.0.255 area 0', isTR ? '3. Yerel LAN ağını Area 0\'a duyur' : '3. Advertise LAN network in Area 0', '(config-router)#'],
        ['network 10.0.0.0 0.0.0.3 area 0', isTR ? '4. WAN bağlantısını Area 0\'a duyur' : '4. Advertise WAN link in Area 0', '(config-router)#'],
        ['show ip ospf neighbor', isTR ? '5. OSPF komşuluk durumunu doğrula' : '5. Verify OSPF neighbor adjacency', '#'],
      ]
    },
    {
      id: 'examples-acl',
      icon: Shield,
      title: isTR ? 'Örnek: Genişletilmiş ACL' : 'Example: Extended ACL',
      type: 'examples',
      cmds: [
        ['access-list 100 deny tcp 192.168.1.0 0.0.0.255 host 10.0.0.5 eq 80', isTR ? '1. 192.168.1.0/24 ağının 10.0.0.5 web sunucusuna (HTTP/80) erişimini engelle' : '1. Block HTTP traffic from 192.168.1.0/24 to 10.0.0.5', '(config)#'],
        ['access-list 100 permit ip any any', isTR ? '2. Diğer tüm trafiğe izin ver' : '2. Permit all other IP traffic', '(config)#'],
        ['interface gi0/0', isTR ? '3. Trafiğin girdiği arayüze gir' : '3. Select inbound interface', '(config)#'],
        ['ip access-group 100 in', isTR ? '4. ACL kuralını arayüzün girişine uygula' : '4. Apply ACL to inbound interface', '(config-if)#'],
        ['show access-lists', isTR ? '5. ACL kurallarını ve eşleşmelerini denetle' : '5. Verify ACL rules and hit count', '#'],
      ]
    },
    {
      id: 'knowledge-stp',
      icon: Book,
      title: isTR ? 'Bilgi: STP Nedir?' : 'Knowledge: What is STP?',
      type: 'info',
      cmds: [
        ['Spanning Tree Protocol', isTR ? 'STP (Spanning Tree Protocol), yerel ağlarda (LAN) fiziksel döngüleri (loop) önlemek için kullanılan bir Layer 2 protokolüdür. Eğer ağda yedekli bağlantılar varsa ve STP yoksa, paketler sonsuz bir döngüye girerek ağı kilitleyebilir (Broadcast Storm). STP, bazı portları bloklayarak döngüsüz bir yapı oluşturur.' : 'STP (Spanning Tree Protocol) is a Layer 2 protocol used to prevent physical loops in local area networks (LANs). If there are redundant links in a network without STP, packets can enter an infinite loop, crashing the network (Broadcast Storm). STP creates a loop-free topology by blocking certain ports.'],
      ]
    },
    {
      id: 'knowledge-dhcp',
      icon: FileText,
      title: isTR ? 'Bilgi: DHCP Nedir?' : 'Knowledge: What is DHCP?',
      type: 'info',
      cmds: [
        ['Dynamic Host Configuration Protocol', isTR ? 'DHCP, ağdaki cihazlara otomatik olarak IP adresi, alt ağ maskesi, varsayılan ağ geçidi ve DNS gibi yapılandırma bilgilerini dağıtan bir protokoldür. Bu sayede her cihazı manuel olarak yapılandırma zahmeti ortadan kalkar ve IP çakışmaları önlenir.' : 'DHCP is a protocol that automatically assigns IP addresses, subnet masks, default gateways, and DNS information to devices on a network. This eliminates the need for manual configuration of each device and helps prevent IP address conflicts.'],
      ]
    },
    {
      id: 'knowledge-vlan',
      icon: Network,
      title: isTR ? 'Bilgi: VLAN Nedir?' : 'Knowledge: What is VLAN?',
      type: 'info',
      cmds: [
        ['Virtual Local Area Network', isTR ? 'VLAN, fiziksel bir yerel ağı mantıksal olarak daha küçük parçalara bölen teknolojidir. Aynı switch üzerindeki kullanıcıları farklı VLAN\'lara ayırarak güvenliği artırabilir ve ağ trafiğini (broadcast) optimize edebilirsiniz. Farklı VLAN\'lar arasındaki iletişim için bir Router veya L3 Switch gerekir.' : 'VLAN is a technology that logically partitions a physical LAN into smaller segments. By placing users on the same switch into different VLANs, you can improve security and optimize network traffic (broadcast). Communication between different VLANs requires a Router or L3 Switch.'],
      ]
    },
    {
      id: 'knowledge-nat',
      icon: Globe,
      title: isTR ? 'Bilgi: NAT & PAT Nedir?' : 'Knowledge: What is NAT & PAT?',
      type: 'info',
      cmds: [
        ['Network Address Translation', isTR ? 'NAT, yerel ağdaki özel (private) IP adreslerini (örn. 192.168.x.x) kamuya açık (public) IP adreslerine dönüştürerek internet erişimi sağlar. Statik NAT birebir eşleşme yaparken, PAT (Port Address Translation / Overload) tek bir public IP üzerinden port numaralarını kullanarak binlerce cihazın aynı anda internete çıkmasını sağlar.' : 'NAT translates private IP addresses (e.g. 192.168.x.x) to public IP addresses for internet access. While Static NAT provides 1-to-1 mapping, PAT (Port Address Translation / Overload) uses unique port numbers on a single public IP to allow thousands of internal hosts to access the internet simultaneously.'],
      ]
    },
    {
      id: 'knowledge-etherchannel',
      icon: Layers,
      title: isTR ? 'Bilgi: EtherChannel Nedir?' : 'Knowledge: What is EtherChannel?',
      type: 'info',
      cmds: [
        ['Link Aggregation / Port Channel', isTR ? 'EtherChannel, 2 ila 8 arasındaki fiziksel Ethernet bağlantısını mantıksal tek bir yüksek hızlı hat (Port-Channel) olarak birleştiren teknolojidir. Hem bant genişliğini artırır hem de fiziksel bir kablo koptuğunda kesintisiz veri akışı (yedeklilik) sağlar. Standart LACP (802.3ad) veya özel PAgP protokolleri ile dinamik kurulabilir.' : 'EtherChannel combines 2 to 8 physical Ethernet links into a single logical high-speed link (Port-Channel). It increases aggregate bandwidth and provides seamless failover redundancy if a link drops. It can be negotiated dynamically using standard LACP (802.3ad) or proprietary PAgP.'],
      ]
    },
    {
      id: 'knowledge-hsrp',
      icon: Server,
      title: isTR ? 'Bilgi: HSRP Nedir?' : 'Knowledge: What is HSRP?',
      type: 'info',
      cmds: [
        ['Hot Standby Router Protocol', isTR ? 'HSRP, birinci ağ geçidinin (Default Gateway) arızalanması durumunda ağ erişiminin kesilmemesi için kullanılan bir yedeklilik protokolüdür. İki veya daha fazla router tek bir Sanal IP (Virtual IP) ve Sanal MAC adresi paylaşır. Aktif (Active) router çöktüğünde Bekleyen (Standby) router milisaniyeler içinde görevi devralır.' : 'HSRP is a redundancy protocol designed to ensure uninterrupted default gateway connectivity. Two or more routers share a single Virtual IP and Virtual MAC address. If the Active router fails, the Standby router seamlessly takes over within milliseconds.'],
      ]
    },
    {
      id: 'knowledge-ospf',
      icon: Network,
      title: isTR ? 'Bilgi: OSPF Nedir?' : 'Knowledge: What is OSPF?',
      type: 'info',
      cmds: [
        ['Open Shortest Path First', isTR ? 'OSPF, açık kaynaklı ve popüler bir Link-State (Bağlantı Durumu) dinamik yönlendirme protokolüdür. En kısa rotayı hesaplamak için Dijkstra (SPF) algoritmasını kullanır. Ağ yapılarını alanlara (Area) bölerek ölçeklenebilirlik sağlar (Area 0 omurgadır). Hızlı uyum sağlama (fast convergence) süresi ile büyük ağlarda tercih edilir.' : 'OSPF is an open standard Link-State dynamic routing protocol using Dijkstra\'s Shortest Path First algorithm. It hierarchically partitions networks into Areas (Area 0 being the backbone) for scalability and provides fast convergence in enterprise networks.'],
      ]
    },
    {
      id: 'knowledge-acl',
      icon: Shield,
      title: isTR ? 'Bilgi: ACL (Erişim Listesi) Nedir?' : 'Knowledge: What is ACL?',
      type: 'info',
      cmds: [
        ['Access Control List', isTR ? 'ACL, ağ cihazlarında geçen paketlerin izin verilip (permit) engelleneceğini (deny) belirleyen kurallar dizisidir. Standart ACL (1-99) sadece kaynak IP adresine bakarken; Genişletilmiş ACL (100-199) kaynak IP, hedef IP, protokol (TCP/UDP/ICMP) ve port numaralarına göre detaylı filtreleme yapar. Her ACL sonuna yazılmayan bir "implicit deny" (örtülü engelleme) kuralı dahildir.' : 'ACL is a set of security rules that filter network traffic by specifying permit or deny conditions. Standard ACLs (1-99) evaluate source IP address only; Extended ACLs (100-199) inspect source IP, destination IP, protocol (TCP/UDP/ICMP), and port numbers. Every ACL has an unwritten "implicit deny" rule at the end.'],
      ]
    },
    {
      id: 'knowledge-ipv6',
      icon: Globe,
      title: isTR ? 'Bilgi: IPv6 & SLAAC Nedir?' : 'Knowledge: What is IPv6 & SLAAC?',
      type: 'info',
      cmds: [
        ['IPv6 & Autoconfiguration', isTR ? 'IPv6, 128-bitlik genişletilmiş adres alanı sunan yeni nesil internet protokolüdür. SLAAC (Stateless Address Autoconfiguration) yöntemi sayesinde cihazlar DHCP sunucusuna ihtiyaç duymadan router önek mesajları (RA) ile otomatik IP yapılandırması alırlar. EUI-64 yöntemi ise cihazın 48-bitlik MAC adresinden benzersiz 64-bitlik Host IP\'si üretir.' : 'IPv6 is the next-generation internet protocol providing a 128-bit address space. With SLAAC (Stateless Address Autoconfiguration), devices receive automatic IP configuration directly via router advertisement (RA) messages without a DHCP server. The EUI-64 mechanism derives a unique 64-bit host address from the device\'s 48-bit MAC address.'],
      ]
    },
    {
      id: 'knowledge-simulation',
      icon: Eye,
      title: isTR ? 'Bilgi: Simülatör ve Araç Kullanımı' : 'Knowledge: Simulator Tools',
      type: 'info',
      cmds: [
        ['NetworkSimulator Kullanım İpuçları', isTR ? 'NetworkSimulator tuvalinde cihazları sürükleyip bırakabilir, portlar arası kablo türünü seçerek (Bakır Düz/Çapraz, Fiber, Seri) bağlayabilirsiniz. Alt paneldeki Paket Yakalama (Packet Capture) sekmesi ile paketlerin OSI katman detaylarını inceleyebilir, Güdümlü Mod (Guided Mode) ile adım adım pratik senaryoları çözebilirsiniz.' : 'In NetworkSimulator, drag-and-drop devices onto the canvas and connect them using appropriate cabling (Copper Straight/Cross, Fiber, Serial). Use the Packet Capture tab to inspect OSI layer encapsulation details, or complete interactive exercises via Guided Mode.'],
      ]
    },
    {
      id: 'packet_trace_diagnostics',
      icon: Eye,
      title: isTR ? 'Paket İzleme & Ağ Teşhis Araçları' : 'Packet & Diagnostics Tools',
      type: 'info',
      cmds: [
        [isTR ? 'Paket İzleme Aracı' : 'Packet Inspector', isTR ? 'Paket simülasyonu esnasında "İzleme Detayı" butonuna basarak Katman 1-7 aşamalarını, kararlarını ve çerçeve anlık görüntülerini (frame snapshot) canlı inceleyebilirsiniz.' : 'Click "Trace Details" during packet simulation to inspect Layer 1-7 pipeline stages, decisions, and frame snapshots.'],
        [isTR ? 'ICMP Hata Kodları' : 'ICMP Error Codes', isTR ? 'ACL engellerinde Code 13 (Admin Prohibited), TTL 0 olduğunda Code 0 (Time Exceeded), rotasız paketlerde Code 0 (Unreachable) ICMP yanıtları üretilir.' : 'Generates ICMP Code 13 for ACL drops, Code 0 for TTL exceeded, and Code 0 for network unreachable.'],
        [isTR ? 'Katman-3 TTL Azaltımı' : 'Layer-3 TTL Decrementing', isTR ? 'Tüm Router ve L3 Switch yönlendirme yollarında paket TTL değeri 1 eksiltilir; 0 olan paketler düşürülür.' : 'Decrements packet TTL by 1 at every L3 hop; drops packets when TTL reaches 0.'],
        [isTR ? 'VLAN & Trunk Teşhisleri' : 'VLAN & Trunk Diagnostics', isTR ? 'Topolojideki bağlı trunk portlar arasındaki Native VLAN uyuşmazlıkları ve Allowed-VLAN farkları otomatik tespit edilir.' : 'Automatically diagnoses Native VLAN and Allowed VLAN mismatches on trunk links.'],
        [isTR ? 'LPM Routing Rasyoneli' : 'LPM Routing Rationale', isTR ? 'Yönlendirme kararları En Uzun Önek Eşleşmesi (LPM), Yönetimsel Mesafe (AD) ve Metrik öncelikleri analiz edilerek gerekçelendirilir ve izleme panelinde gösterilir.' : 'Explains routing decisions based on Longest-Prefix Match (LPM), Administrative Distance (AD), and Metric.'],
      ]
    },
    {
      id: 'firewall',
      icon: Shield,
      title: isTR ? 'Güvenlik Duvarı (ASA/Firewall)' : 'Firewall (ASA)',
      type: 'commands',
      cmds: [
        ['nameif <name>', isTR ? 'Arayüz adını belirle' : 'Set interface name', '(config-if)#'],
        ['no nameif', isTR ? 'Arayüz adını sil' : 'Remove interface name', '(config-if)#'],
        ['security-level <0-100>', isTR ? 'Güvenlik seviyesi ata' : 'Set security level', '(config-if)#'],
        ['ip access-group <id> {in|out}', isTR ? 'ACL\'yi arayüze uygula' : 'Apply ACL to interface', '(config-if)#'],
        ['show nameif', isTR ? 'Arayüz adlarını göster' : 'Show interface names', '#'],
        ['show ip access-group', isTR ? 'ACL uygulamalarını göster' : 'Show applied ACLs', '#'],
      ]
    },
    {
      id: 'acl',
      icon: Shield,
      title: isTR ? 'Erişim Kontrol Listeleri (ACL)' : 'Access Control Lists (ACL)',
      type: 'commands',
      cmds: [
        ['access-list <1-99> {permit|deny} <source> [wildcard]', isTR ? 'Standart numaralı ACL kuralı oluştur' : 'Create standard numbered ACL rule', '(config)#'],
        ['access-list <100-199> {permit|deny} <protocol> <source> <dest> [operator port]', isTR ? 'Genişletilmiş numaralı ACL kuralı oluştur' : 'Create extended numbered ACL rule', '(config)#'],
        ['no access-list <id>', isTR ? 'Numaralı ACL\'yi sil' : 'Remove numbered ACL', '(config)#'],
        ['ip access-list {standard|extended} <name>', isTR ? 'Adlandırılmış ACL oluştur' : 'Create named ACL', '(config)#'],
        ['no ip access-list {standard|extended} <name>', isTR ? 'Adlandırılmış ACL\'yi sil' : 'Remove named ACL', '(config)#'],
        ['permit <rule>', isTR ? 'İzin verme kuralı (ACL modunda)' : 'Permit rule (in ACL mode)', '(config-std-nacl)#'],
        ['deny <rule>', isTR ? 'Engelleme kuralı (ACL modunda)' : 'Deny rule (in ACL mode)', '(config-std-nacl)#'],
        ['ip access-group <id|name> {in|out}', isTR ? 'ACL\'yi IP arayüzüne uygula' : 'Apply ACL to IP interface', '(config-if)#'],
        ['show access-lists [<id|name>]', isTR ? 'Tanımlı ACL\'leri ve kuralları göster' : 'Display defined ACLs and rules', '#'],
      ]
    },
    {
      id: 'wlc',
      icon: Radio,
      title: isTR ? 'WLC / AP Yönetimi' : 'WLC / AP Management',
      type: 'commands',
      cmds: [
        ['ap name <name>', isTR ? 'Access Point adlandır' : 'Name the Access Point', '(config)#'],
        ['ap auth-mac <mac>', isTR ? 'AP MAC adres yetkilendirmesi' : 'AP MAC address authorization', '(config)#'],
        ['ap rf-channel <num>', isTR ? 'AP RF kanalını ayarla' : 'Set AP RF channel', '(config)#'],
        ['show ap summary', isTR ? 'AP özetini göster' : 'Show AP summary', '#'],
        ['show ap config [name]', isTR ? 'AP yapılandırmasını göster' : 'Show AP configuration', '#'],
        ['show ap join statistics [name]', isTR ? 'AP katılım istatistiklerini göster' : 'Show AP join statistics', '#'],
        ['show wlan summary', isTR ? 'WLAN özetini göster' : 'Show WLAN summary', '#'],
        ['show wlan <id>', isTR ? 'WLAN detaylarını göster' : 'Show WLAN details', '#'],
      ]
    },
    {
      id: 'interface',
      icon: Settings,
      title: isTR ? 'Arayüz Yapılandırması' : 'Interface Config',
      type: 'commands',
      cmds: [
        ['shutdown', isTR ? 'Arayüzü kapat' : 'Disable interface', '(config-if)#'],
        ['no shutdown', isTR ? 'Arayüzü aç' : 'Enable interface', '(config-if)#'],
        ['speed {10|100|1000|10000|auto}', isTR ? 'Hız ayarla' : 'Set speed', '(config-if)#'],
        ['duplex {half|full|auto}', isTR ? 'Duplex ayarla' : 'Set duplex', '(config-if)#'],
        ['description <text>', isTR ? 'Arayüz açıklaması' : 'Set description', '(config-if)#'],
        ['no description', isTR ? 'Açıklamayı sil' : 'Clear description', '(config-if)#'],
        ['switchport mode access', isTR ? 'Erişim modu' : 'Access mode', '(config-if)#'],
        ['switchport mode trunk', isTR ? 'Trunk modu' : 'Trunk mode', '(config-if)#'],
        ['switchport trunk encapsulation dot1q', isTR ? 'Trunk kapsülleme' : 'Trunk encapsulation', '(config-if)#'],
        ['encapsulation dot1q <vlan>', isTR ? 'Subinterface VLANı' : 'Subinterface VLAN', '(config-subif)#'],
        ['switchport mode dynamic {m}', isTR ? 'DTP modu' : 'Set DTP mode', '(config-if)#'],
        ['switchport mode dot1q-tunnel', isTR ? 'Dot1q tunnel' : 'Dot1q tunnel mode', '(config-if)#'],
        ['no switchport mode', isTR ? 'Modu sıfırla' : 'Reset switchport mode', '(config-if)#'],
        ['switchport access vlan <id>', isTR ? 'VLAN ata' : 'Assign VLAN', '(config-if)#'],
        ['no switchport access vlan', isTR ? 'VLAN atamasını sil' : 'Remove VLAN assign', '(config-if)#'],
        ['switchport trunk native <id>', isTR ? 'Native VLAN' : 'Set native VLAN', '(config-if)#'],
        ['switchport trunk allowed <l>', isTR ? 'İzinli VLANlar' : 'Set allowed VLANs', '(config-if)#'],
        ['switchport nonegotiate', isTR ? 'DTP\'yi kapat' : 'Disable DTP', '(config-if)#'],
        ['switchport voice vlan <id>', isTR ? 'Ses VLAN\'ı' : 'Set voice VLAN', '(config-if)#'],
        ['switchport port-security', isTR ? 'Port güvenliği' : 'Port security', '(config-if)#'],
        ['switchport port-security max <n>', isTR ? 'Maksimum MAC' : 'Set max MACs', '(config-if)#'],
        ['switchport port-security violation {a}', isTR ? 'İhlal aksiyonu' : 'Violation action', '(config-if)#'],
        ['switchport port-security sticky', isTR ? 'Sticky MAC' : 'Enable sticky MAC', '(config-if)#'],
        ['switchport port-security aging time <n>', isTR ? 'Güvenlik yaşlanma süresi' : 'Port-security aging time', '(config-if)#'],
        ['no switchport port-security', isTR ? 'Güvenliği kapat' : 'Disable port security', '(config-if)#'],
        ['switchport protected', isTR ? 'Korumalı port' : 'Protected port', '(config-if)#'],
        ['switchport block {unicast|multicast}', isTR ? 'Trafik bloklama' : 'Block traffic', '(config-if)#'],
        ['no switchport', isTR ? 'L3 portuna dönüştür' : 'Convert to L3 port', '(config-if)#'],
        ['spanning-tree portfast', isTR ? 'PortFast aç' : 'Enable PortFast', '(config-if)#'],
        ['spanning-tree bpduguard {e|d}', isTR ? 'BPDU Guard' : 'BPDU Guard', '(config-if)#'],
        ['spanning-tree cost <cost>', isTR ? 'STP maliyeti' : 'Set STP cost', '(config-if)#'],
        ['spanning-tree priority <p>', isTR ? 'STP önceliği' : 'Set STP priority', '(config-if)#'],
        ['ip address <ip> <mask>', isTR ? 'IP adresi ata' : 'Set IP address', '(config-if)#'],
        ['ipv6 address <ip>/<p>', isTR ? 'IPv6 adresi ata' : 'Set IPv6 address', '(config-if)#'],
        ['no ip address', isTR ? 'IP adresini sil' : 'Remove IP address', '(config-if)#'],
        ['ip default-gateway <ip>', isTR ? 'Arayüz gateway' : 'Interface gateway', '(config-if)#'],
        ['no ip default-gateway', isTR ? 'Gateway sil' : 'Remove gateway', '(config-if)#'],
        ['ip helper-address <ip>', isTR ? 'DHCP relay' : 'Set DHCP relay', '(config-if)#'],
        ['no ip helper-address', isTR ? 'DHCP relay sil' : 'Remove DHCP relay', '(config-if)#'],
        ['ip verify source', isTR ? 'IP Source Guard' : 'Enable Source Guard', '(config-if)#'],
        ['ip dhcp snooping trust', isTR ? 'Güvenli DHCP portu' : 'DHCP snooping trust', '(config-if)#'],
        ['ip arp inspection trust', isTR ? 'Güvenli ARP portu' : 'ARP inspection trust', '(config-if)#'],
        ['storm-control {b|m|u} lvl', isTR ? 'Fırtına kontrolü' : 'Storm control', '(config-if)#'],
        ['power inline {auto|static}', isTR ? 'PoE yapılandırması' : 'Configure PoE', '(config-if)#'],
        ['bandwidth <kbps>', isTR ? 'Bant genişliği' : 'Set bandwidth', '(config-if)#'],
        ['delay <tens-of-ms>', isTR ? 'Gecikme süresi' : 'Set delay', '(config-if)#'],
        ['mls qos trust {cos|dscp}', isTR ? 'QoS güven durumu' : 'Set QoS trust', '(config-if)#'],
        ['mls qos cos <val>', isTR ? 'Default CoS değeri' : 'Set default CoS', '(config-if)#'],
        ['cdp enable', isTR ? 'CDP\'yi aç (arayüz)' : 'Enable CDP (interface)', '(config-if)#'],
        ['no udld', isTR ? 'UDLD\'yi kapat' : 'Disable UDLD', '(config-if)#'],
        ['no ip proxy-arp', isTR ? 'Proxy ARP kapat' : 'Disable proxy ARP', '(config-if)#'],
        ['no keepalive', isTR ? 'Keepalive kapat' : 'Disable keepalive', '(config-if)#'],
        ['load-interval <sec>', isTR ? 'İstatistik aralığı' : 'Set load interval', '(config-if)#'],
        ['carrier-delay <ms>', isTR ? 'Carrier gecikmesi' : 'Set carrier delay', '(config-if)#'],
        ['channel-group <n> mode', isTR ? 'EtherChannel' : 'EtherChannel', '(config-if)#'],
        ['no channel-group', isTR ? 'EtherChannel sil' : 'Remove from channel', '(config-if)#'],
        ['encapsulation hdlc', isTR ? 'HDLC kapsülleme (seri)' : 'HDLC encapsulation (serial)', '(config-if)#'],
        ['encapsulation ppp', isTR ? 'PPP kapsülleme (seri)' : 'PPP encapsulation (serial)', '(config-if)#'],
        ['clock rate <bps>', isTR ? 'Saat hızı (DCE seri)' : 'Clock rate (DCE serial)', '(config-if)#'],
        ['ppp authentication pap', isTR ? 'PPP PAP kimlik doğrulama' : 'PPP PAP authentication', '(config-if)#'],
        ['ppp authentication chap', isTR ? 'PPP CHAP kimlik doğrulama' : 'PPP CHAP authentication', '(config-if)#'],
        ['ppp pap sent-username <u> <p>', isTR ? 'PAP kullanıcı adı/şifre' : 'PAP username/password', '(config-if)#'],
        ['ip access-group <id> {in|out}', isTR ? 'ACL uygula' : 'Apply ACL', '(config-if)#'],
        ['ip nat {inside|outside}', isTR ? 'NAT tarafı seç' : 'Set NAT side', '(config-if)#'],
        ['standby <g> ip <vip>', isTR ? 'HSRP Virtual IP' : 'HSRP Virtual IP', '(config-if)#'],
        ['standby <g> priority <p>', isTR ? 'HSRP Önceliği' : 'HSRP Priority', '(config-if)#'],
        ['glbp <g> ip <vip>', isTR ? 'GLBP Sanal IP Adresi' : 'GLBP Virtual IP Address', '(config-if)#'],
        ['glbp <g> priority <p>', isTR ? 'GLBP Önceliği (AVG seçimi)' : 'GLBP Priority (AVG election)', '(config-if)#'],
        ['glbp <g> preempt', isTR ? 'GLBP Preemption (Geri devralma)' : 'GLBP Preemption mode', '(config-if)#'],
        ['ip flow {ingress|egress}', isTR ? 'Arayüzde NetFlow izleme aç' : 'Enable NetFlow monitoring on interface', '(config-if)#'],
        ['spanning-tree guard loop', isTR ? 'Arayüzde Loop Guard aç' : 'Enable Loop Guard on interface', '(config-if)#'],
        ['ipv6 eigrp <as>', isTR ? 'IPv6 EIGRP\'yi arayüzde etkinleştir' : 'Enable IPv6 EIGRP on interface', '(config-if)#'],
        ['monitor session <n>', isTR ? 'SPAN/RSPAN' : 'Configure SPAN/RSPAN', '(config-if)#'],
      ]
    },
    {
      id: 'wireless',
      icon: Wifi,
      title: isTR ? 'Kablosuz (WiFi / Dot11)' : 'Wireless (WiFi / Dot11)',
      type: 'commands',
      cmds: [
        ['dot11 ssid <name>', isTR ? 'SSID yapılandırmasına gir' : 'Enter SSID config', '(config)#'],
        ['authentication open', isTR ? 'Açık kimlik doğrulama' : 'Open authentication', '(config-ssid)#'],
        ['authentication shared', isTR ? 'Paylaşımlı kimlik doğrulama' : 'Shared authentication', '(config-ssid)#'],
        ['authentication network-eap', isTR ? 'EAP kimlik doğrulama' : 'EAP authentication', '(config-ssid)#'],
        ['authentication key-management wpa version {1|2}', isTR ? 'WPA anahtar yönetimi' : 'WPA key management', '(config-ssid)#'],
        ['wpa-psk ascii <key>', isTR ? 'WPA ön-paylaşımlı anahtar' : 'WPA pre-shared key', '(config-ssid)#'],
        ['guest-mode', isTR ? 'SSID\'yi yayınla (Beacon)' : 'Broadcast SSID (Beacon)', '(config-ssid)#'],
        ['no guest-mode', isTR ? 'SSID yayınını kapat' : 'Stop SSID broadcast', '(config-ssid)#'],
        ['wlan <name> <id> <ssid>', isTR ? 'WLAN oluştur (kontrol cihazı)' : 'Create WLAN (controller)', '(config)#'],
        ['no wlan <id>', isTR ? 'WLAN sil' : 'Delete WLAN', '(config)#'],
        ['security wpa psk set-key ascii 0 <pass>', isTR ? 'WPA şifresi ayarla (WLAN)' : 'Set WPA password (WLAN)', '(config-wlan)#'],
        ['interface Dot11Radio <n>', isTR ? 'Radyo arayüzüne gir' : 'Enter radio interface', '(config)#'],
        ['encryption mode ciphers {aes-ccm|tkip}', isTR ? 'şifreleme yöntemi' : 'Encryption method', '(config-if)#'],
        ['ssid <name>', isTR ? 'SSID\'yi radyo arayüzüne bağla' : 'Bind SSID to radio interface', '(config-if)#'],
        ['no ssid <name>', isTR ? 'SSID bağlantısını kaldır' : 'Remove SSID binding', '(config-if)#'],
        ['channel <num>', isTR ? 'RF kanalı ayarla' : 'Set RF channel', '(config-if)#'],
        ['power local <mw>', isTR ? 'İletim gücü ayarla' : 'Set transmit power', '(config-if)#'],
        ['station-role {root|repeater|client}', isTR ? 'AP çalışma modu' : 'AP role mode', '(config-if)#'],
        ['mac-filter', isTR ? 'MAC filtrelemeyi aç' : 'Enable MAC filtering', '(config-if)#'],
        ['no mac-filter', isTR ? 'MAC filtrelemeyi kapat' : 'Disable MAC filtering', '(config-if)#'],
        ['show dot11 associations', isTR ? 'Kablosuz istemcileri göster' : 'Show wireless clients', '#'],
        ['show dot11 statistics', isTR ? 'Kablosuz istatistikleri' : 'Show wireless statistics', '#'],
      ]
    },
    {
      id: 'line',
      icon: Router,
      title: isTR ? 'Hat Yapılandırması' : 'Line Config',
      type: 'commands',
      cmds: [
        ['line console 0', isTR ? 'Konsol hattı' : 'Console line', '(config)#'],
        ['line vty 0 4', isTR ? 'VTY hatları (0-4)' : 'VTY lines (0-4)', '(config)#'],
        ['line vty 5 15', isTR ? 'VTY hatları (5-15)' : 'VTY lines (5-15)', '(config)#'],
        ['line aux 0', isTR ? 'Aux hattı' : 'Auxiliary line', '(config)#'],
        ['password <pass>', isTR ? 'şifre ayarla' : 'Set password', '(config-line)#'],
        ['no password', isTR ? 'şifreyi sil' : 'Remove password', '(config-line)#'],
        ['login', isTR ? 'Giriş kontrolü' : 'Enable login', '(config-line)#'],
        ['no login', isTR ? 'Giriş kontrolü kapat' : 'Disable login', '(config-line)#'],
        ['transport input {p}', isTR ? 'Giriş protokolleri' : 'Input protocols', '(config-line)#'],
        ['transport output {p}', isTR ? 'Çıkış protokolleri' : 'Output protocols', '(config-line)#'],
        ['no transport input', isTR ? 'Girişleri sıfırla' : 'Reset transport input', '(config-line)#'],
        ['logging synchronous', isTR ? 'Senkron loglama' : 'Sync logging', '(config-line)#'],
        ['no logging synchronous', isTR ? 'Senkron log kapat' : 'Disable sync logging', '(config-line)#'],
        ['exec-timeout <m> [s]', isTR ? 'Zaman aşımı' : 'Exec timeout', '(config-line)#'],
        ['no exec-timeout', isTR ? 'Zaman aşımı sıfırla' : 'Reset exec timeout', '(config-line)#'],
        ['history size <n>', isTR ? 'Geçmiş boyutu' : 'Set history size', '(config-line)#'],
        ['no history', isTR ? 'Geçmişi kapat' : 'Disable history', '(config-line)#'],
        ['exec', isTR ? 'EXEC aktif' : 'Enable EXEC', '(config-line)#'],
        ['no exec', isTR ? 'EXEC pasif' : 'Disable EXEC', '(config-line)#'],
        ['autocommand <cmd>', isTR ? 'Otomatik komut' : 'Set auto-command', '(config-line)#'],
        ['no autocommand', isTR ? 'Otomatik komut sil' : 'Remove auto-command', '(config-line)#'],
        ['transport preferred {ssh|telnet|none}', isTR ? 'Tercih edilen protokol' : 'Preferred protocol', '(config-line)#'],
        ['privilege level <0-15>', isTR ? 'Yetki seviyesi' : 'Set privilege level', '(config-line)#'],
        ['session-limit <n>', isTR ? 'Oturum sınırı' : 'Session limit', '(config-line)#'],
        ['access-class <n> {in|out}', isTR ? 'ACL uygula (line)' : 'Apply access-class', '(config-line)#'],
        ['lockable', isTR ? 'Kilitlenebilir hat' : 'Enable lockable', '(config-line)#'],
      ]
    },
    {
      id: 'administration',
      icon: Server,
      title: isTR ? 'Yönetim' : 'Administration',
      type: 'commands',
      cmds: [
        ['disconnect <session>', isTR ? 'Oturumu kes' : 'Disconnect session', '(config)#'],
        ['resume <session>', isTR ? 'Oturuma devam et' : 'Resume session', '(config)#'],
        ['suspend', isTR ? 'Oturumu askıya al' : 'Suspend session', '(config)#'],
        ['setup', isTR ? 'Kurulum sihirbazı' : 'Setup wizard', '(config)#'],
        ['test', isTR ? 'Tanılama testi' : 'Diagnostic test', '(config)#'],
        ['configure replace <url>', isTR ? 'Yapılandırmayı dosyadan değiştir' : 'Replace config from file', '(config)#'],
        ['archive', isTR ? 'Arşiv yapılandırması' : 'Archive configuration', '(config)#'],
        ['terminal length <0-512>', isTR ? 'Terminal satır uzunluğu' : 'Set terminal length', '(config)#'],
        ['terminal width <n>', isTR ? 'Terminal genişliği' : 'Set terminal width', '(config)#'],
        ['terminal monitor', isTR ? 'Log mesajlarını görüntüle' : 'Monitor log messages', '(config)#'],
        ['terminal no monitor', isTR ? 'Log görüntülemeyi kapat' : 'Stop monitoring logs', '(config)#'],
        ['help', isTR ? 'Yardım sistemini göster' : 'Display help system', '(config)#'],
        ['alias <mode> <name> <cmd>', isTR ? 'Komut takma adı' : 'Create command alias', '(config)#'],
        ['no alias <name>', isTR ? 'Alias sil' : 'Remove command alias', '(config)#'],
        ['more <filename>', isTR ? 'Dosya içeriğini göster' : 'Display file contents', '(config)#'],
        ['clear terminal', isTR ? 'Terminalı temizle' : 'Clear terminal', '(config)#'],
        ['clear line <n>', isTR ? 'Hattı sil' : 'Clear line', '(config)#'],
        ['access-class <n> {in|out}', isTR ? 'ACL uygula' : 'Apply access-class', '(config)#'],
        ['lockable', isTR ? 'Kilitlenebilir hat' : 'Enable lockable', '(config)#'],
        ['exec', isTR ? 'EXEC aktif' : 'Enable EXEC', '(config)#'],
        ['no exec', isTR ? 'EXEC pasif' : 'Disable EXEC', '(config)#'],
        ['autocommand <cmd>', isTR ? 'Otomatik komut' : 'Set auto-command', '(config)#'],
        ['no autocommand', isTR ? 'Otomatik komut sil' : 'Remove auto-command', '(config)#'],
        ['transport preferred {ssh|telnet|none}', isTR ? 'Tercih edilen protokol' : 'Preferred protocol', '(config)#'],
        ['privilege level <0-15>', isTR ? 'Yetki seviyesi' : 'Set privilege level', '(config)#'],
        ['session-limit <n>', isTR ? 'Oturum sınırı' : 'Session limit', '(config)#'],
      ]
    },
    {
      id: 'router',
      icon: Network,
      title: isTR ? 'Yönlendirme (Routing)' : 'Routing Config',
      type: 'commands',
      cmds: [
        ['router rip', isTR ? 'RIP yönlendirmesi' : 'Enable RIP', '(config)#'],
        ['router ospf [<id>]', isTR ? 'OSPF yönlendirmesi' : 'Enable OSPF', '(config)#'],
        ['router eigrp <as>', isTR ? 'EIGRP yönlendirmesi' : 'Enable EIGRP', '(config)#'],
        ['router bgp <as>', isTR ? 'BGP yönlendirmesi' : 'Enable BGP', '(config)#'],
        ['no router {rip|ospf|eigrp|bgp}', isTR ? 'Yönlendirmeyi kapat' : 'Disable routing', '(config)#'],
        ['network <ip> [wildcard]', isTR ? 'Ağ ekle (RIP/EIGRP)' : 'Add network (RIP/EIGRP)', '(config-router)#'],
        ['network <ip> area <id>', isTR ? 'OSPF ağı ekle' : 'Add OSPF network', '(config-router)#'],
        ['neighbor <ip> remote-as <as>', isTR ? 'BGP komşusu ekle' : 'Add BGP neighbor', '(config-router)#'],
        ['neighbor <ip> route-map <map> {in|out}', isTR ? 'BGP komşusuna Route-Map kuralı bağla' : 'Bind Route-Map policy to BGP neighbor', '(config-router)#'],
        ['neighbor <ip> weight <value>', isTR ? 'BGP komşu rota ağırlığı (Weight) ata' : 'Set BGP neighbor route weight', '(config-router)#'],
        ['no neighbor <ip> remote-as', isTR ? 'BGP komşusunu sil' : 'Remove BGP neighbor', '(config-router)#'],

        ['router-id <ip>', isTR ? 'Router ID ayarla' : 'Set router ID', '(config-router)#'],
        ['passive-interface <int>', isTR ? 'Pasif arayüz' : 'Passive interface', '(config-router)#'],
        ['no passive-interface <int>', isTR ? 'Pasif arayüz kaldır' : 'Remove passive interface', '(config-router)#'],
        ['default-info originate', isTR ? 'Varsayılan rota' : 'Default route', '(config-router)#'],
        ['auto-summary', isTR ? 'Otomatik özetleme' : 'Auto-summary', '(config-router)#'],
        ['no auto-summary', isTR ? 'Otomatik özetlemeyi kapat' : 'Disable auto-summary', '(config-router)#'],
        ['ipv6 router rip <tag>', isTR ? 'IPv6 RIP yönlendirmesi' : 'Enable IPv6 RIP', '(config)#'],
        ['ipv6 router ospf <id>', isTR ? 'IPv6 OSPF yönlendirmesi' : 'Enable IPv6 OSPF', '(config)#'],
        ['no ipv6 router rip <tag>', isTR ? 'IPv6 RIP kapat' : 'Disable IPv6 RIP', '(config)#'],
        ['no ipv6 router ospf <id>', isTR ? 'IPv6 OSPF kapat' : 'Disable IPv6 OSPF', '(config)#'],
        ['show ip route', isTR ? 'Yönlendirme tablosu' : 'Show routing table', '#'],
        ['show ip ospf [neighbor|interface]', isTR ? 'OSPF detayları' : 'Show OSPF details', '#'],
        ['show ip protocols', isTR ? 'Yönlendirme protokolleri' : 'Show routing protocols', '#'],
        ['show ip eigrp neighbors', isTR ? 'EIGRP komşuları' : 'Show EIGRP neighbors', '#'],
        ['show ip bgp summary', isTR ? 'BGP özeti' : 'Show BGP summary', '#'],
        ['show ip bgp', isTR ? 'BGP tablosu' : 'Show BGP table', '#'],
        ['show ipv6 route', isTR ? 'IPv6 yönlendirme tablosu' : 'Show IPv6 routing table', '#'],
        ['show ipv6 rip', isTR ? 'IPv6 RIP durumu' : 'Show IPv6 RIP status', '#'],
        ['show ipv6 ospf', isTR ? 'IPv6 OSPF durumu' : 'Show IPv6 OSPF status', '#'],
      ]
    },
    {
      id: 'dhcp',
      icon: Server,
      title: isTR ? 'DHCP Havuzu' : 'DHCP Pool Config',
      type: 'commands',
      cmds: [
        ['network <net> <mask>', isTR ? 'Havuz ağı' : 'Pool network', '(config-dhcp)#'],
        ['default-router <ip>', isTR ? 'Varsayılan geçit' : 'Default router', '(config-dhcp)#'],
        ['dns-server <ip>', isTR ? 'DNS sunucusu' : 'DNS server', '(config-dhcp)#'],
        ['lease {days|infinite}', isTR ? 'Kira süresi' : 'Lease duration', '(config-dhcp)#'],
        ['domain-name <name>', isTR ? 'Alan adı' : 'Domain name', '(config-dhcp)#'],
      ]
    },
    {
      id: 'show',
      icon: Eye,
      title: isTR ? 'Show Komutları' : 'Show Commands',
      type: 'commands',
      cmds: [
        ['show', isTR ? 'Özet bilgi' : 'Display summary', '#'],
        ['show running-config', isTR ? 'Çalışan yapılandırma' : 'Running config', '#'],
        ['show startup-config', isTR ? 'Başlangıç yapılandırması' : 'Startup config', '#'],
        ['show version', isTR ? 'Sistem bilgisi' : 'System version', '#'],
        ['show interfaces', isTR ? 'Tüm arayüzler' : 'Display all interfaces', '#'],
        ['show interfaces trunk', isTR ? 'Trunk arayüzler' : 'Display trunks', '#'],
        ['show interface <name>', isTR ? 'Arayüz ayrıntısı' : 'Interface details', '#'],
        ['show ip interface brief', isTR ? 'Arayüz özeti' : 'IP interface brief', '#'],
        ['show ip interface', isTR ? 'IP arayüz detay' : 'IP interface details', '#'],
        ['show ip protocols', isTR ? 'Yönlendirme protokolleri' : 'IP routing protocols', '#'],
        ['show ip ospf [neighbor|interface]', isTR ? 'OSPF detayları' : 'OSPF details', '#'],
        ['show ip nat translations', isTR ? 'NAT çevirileri' : 'NAT translations', '#'],
        ['show ip nat statistics', isTR ? 'NAT istatistikleri' : 'NAT statistics', '#'],
        ['show standby [brief]', isTR ? 'HSRP durumu' : 'HSRP status', '#'],
        ['show ip arp', isTR ? 'ARP tablosu' : 'ARP table', '#'],
        ['show ipv6 interface brief', isTR ? 'IPv6 arayüz özeti' : 'IPv6 interface brief', '#'],
        ['show vlan [brief]', isTR ? 'VLAN listesi' : 'VLAN list', '#'],
        ['show mac address-table', isTR ? 'MAC tablosunu göster' : 'Show MAC address table', '#'],
        ['show cdp neighbors', isTR ? 'CDP komşuları' : 'CDP neighbors', '#'],
        ['show ip route', isTR ? 'Yönlendirme tablosu' : 'Routing table', '#'],
        ['show clock', isTR ? 'Sistem saati' : 'Display system clock', '#'],
        ['show flash', isTR ? 'Flash içeriği' : 'Display flash', '#'],
        ['show boot', isTR ? 'Boot bilgisi' : 'Display boot info', '#'],
        ['show spanning-tree', isTR ? 'STP durumu' : 'STP status', '#'],
        ['show port-security', isTR ? 'Port güvenliği' : 'Port security status', '#'],
        ['show ssh', isTR ? 'SSH durumu' : 'SSH status', '#'],
        ['show crypto isakmp sa', isTR ? 'ISAKMP SA güvenlik durumunu göster' : 'Show ISAKMP SA status', '#'],
        ['show crypto ipsec sa', isTR ? 'IPsec SA tünel istatistiklerini göster' : 'Show IPsec SA statistics', '#'],
        ['show crypto map', isTR ? 'Crypto Map haritalarını göster' : 'Show Crypto Map entries', '#'],
        ['show wireless', isTR ? 'Kablosuz durumu' : 'Display wireless status', '#'],

        ['show ip dhcp snooping', isTR ? 'DHCP snooping' : 'Display DHCP snooping', '#'],
        ['show ip dhcp pool', isTR ? 'DHCP havuzları' : 'Display DHCP pools', '#'],
        ['show ip dhcp binding', isTR ? 'DHCP atamaları' : 'DHCP bindings', '#'],
        ['show ip verify source', isTR ? 'Source Guard durumu' : 'IP source guard status', '#'],
        ['show ip source binding', isTR ? 'Source bindingleri' : 'IP source bindings', '#'],
        ['show ip arp inspection', isTR ? 'ARP denetimi' : 'ARP inspection status', '#'],
        ['show interfaces status', isTR ? 'Arayüz durumu' : 'Display port status', '#'],
        ['show storm-control', isTR ? 'Fırtına kontrolü' : 'Storm control status', '#'],
        ['show monitor', isTR ? 'SPAN oturumları' : 'SPAN sessions', '#'],
        ['show udld', isTR ? 'UDLD durumu' : 'UDLD status', '#'],
        ['show cdp', isTR ? 'CDP bilgisi' : 'Display CDP info', '#'],
        ['show vtp status', isTR ? 'VTP durumu' : 'Display VTP status', '#'],
        ['show etherchannel', isTR ? 'EtherChannel' : 'Display EtherChannel', '#'],
        ['show arp', isTR ? 'ARP tablosu' : 'ARP table', '#'],
        ['show mls qos', isTR ? 'QoS durumu' : 'Display QoS status', '#'],
        ['show sdm prefer', isTR ? 'SDM şablonu' : 'Display SDM template', '#'],
        ['show access-lists', isTR ? 'Erişim listeleri' : 'Display access lists', '#'],
        ['show mac access-lists', isTR ? 'MAC erişim listeleri' : 'Display MAC ACLs', '#'],
        ['show history', isTR ? 'Komut geçmişi' : 'Display command history', '#'],
        ['show users', isTR ? 'Kullanıcılar' : 'Connected users', '#'],
        ['show environment', isTR ? 'Donanım durumu' : 'Display hardware status', '#'],
        ['show inventory', isTR ? 'Donanım envanteri' : 'Display inventory', '#'],
        ['show errdisable recovery', isTR ? 'Hata kurtarma' : 'Display errdisable', '#'],
        ['show debug', isTR ? 'Debug durumu' : 'Display debug status', '#'],
        ['show processes', isTR ? 'İşlemler (CPU)' : 'Display processes', '#'],
        ['show memory', isTR ? 'Bellek kullanımı' : 'Display memory usage', '#'],
        ['show system mtu', isTR ? 'MTU ayarları' : 'Display MTU settings', '#'],
        ['show ntp status', isTR ? 'NTP durumu' : 'Display NTP status', '#'],
        ['show snmp', isTR ? 'SNMP bilgisi' : 'Display SNMP info', '#'],
        ['show archive', isTR ? 'Arşiv durumu' : 'Display archive status', '#'],
        ['show alias', isTR ? 'Alias listesi' : 'Display command aliases', '#'],
        ['show diagnostic', isTR ? 'Teşhis sonuçları' : 'Display diagnostics', '#'],
        ['show lldp', isTR ? 'LLDP komşuları' : 'Display LLDP info', '#'],
        ['show authentication', isTR ? 'Kimlik doğrulama' : 'Display auth sessions', '#'],
        ['show running-config interface <name>', isTR ? 'Arayüz yapılandırması' : 'Show interface config', '#'],
        ['show spanning-tree interface <name>', isTR ? 'Arayüz STP durumu' : 'Show interface STP status', '#'],
        ['show ip ssh', isTR ? 'SSH yapılandırması' : 'Show SSH configuration', '#'],
        ['show cdp neighbors detail', isTR ? 'CDP komşuları detaylı' : 'Show CDP neighbor details', '#'],
        ['show policy-map [name]', isTR ? 'Politika haritası' : 'Show policy map', '#'],
        ['show policy-map interface', isTR ? 'Arayüz politika haritası' : 'Show interface policy map', '#'],
        ['show class-map [name]', isTR ? 'Sınıf haritası' : 'Show class map', '#'],
        ['show qos interface <name>', isTR ? 'Arayüz QoS durumu' : 'Show interface QoS', '#'],
        ['show queuing interface <name>', isTR ? 'Arayüz kuyruk durumu' : 'Show interface queuing', '#'],
        ['show ip ospf interface <name>', isTR ? 'OSPF arayüz durumu' : 'Show OSPF interface', '#'],
        ['show ipv6 route', isTR ? 'IPv6 yönlendirme tablosu' : 'Show IPv6 routing table', '#'],
        ['show ipv6 dhcp pool', isTR ? 'IPv6 DHCP havuzu' : 'Show IPv6 DHCP pool', '#'],
        ['show mac address-table static', isTR ? 'Statik MAC adresleri' : 'Show static MAC addresses', '#'],
        ['show sessions', isTR ? 'Aktif oturumlar' : 'Show active sessions', '#'],
        ['show ntp associations', isTR ? 'NTP ilişkileri' : 'Show NTP associations', '#'],
        ['show hosts', isTR ? 'Host tablosu' : 'Show host table', '#'],
        ['show debugging', isTR ? 'Hata ayıklama durumu' : 'Show debug status', '#'],
        ['show errdisable detect', isTR ? 'Hata algılama ayarları' : 'Show errdisable detection', '#'],
        ['show redundancy', isTR ? 'Yedeklilik durumu' : 'Show redundancy status', '#'],
        ['show controllers <type/n>', isTR ? 'Denetleyici durumu' : 'Show controller status', '#'],
        ['show banner motd', isTR ? 'MOTD banner mesajı' : 'Show MOTD banner', '#'],

      ]
    },
    {
      id: 'desktop',
      icon: Terminal,
      title: isTR ? 'Masaüstü Bilgisayar' : 'Desktop Computer',
      type: 'commands',
      cmds: [
        ['ipconfig [/all] [/release] [/renew]', isTR ? 'IP yapılandırması' : 'IP configuration'],
        ['ping <host>', isTR ? 'Bağlantı testi' : 'Test connectivity'],
        ['tracert <host>', isTR ? 'Rota izleme' : 'Trace route'],
        ['netstat', isTR ? 'Ağ istatistikleri' : 'Network statistics'],
        ['nslookup <domain>', isTR ? 'DNS sorgusu' : 'DNS lookup'],
        ['ftp <host>', isTR ? 'FTP bağlantısı' : 'FTP connection'],
        ['telnet <host> [port]', isTR ? 'Telnet bağlantısı' : 'Telnet connection'],
        ['ssh [-l user] <host>', isTR ? 'SSH bağlantısı' : 'SSH connection'],
        ['curl <url>', isTR ? 'Web sayfası içeriğini al (cURL)' : 'Fetch web content (cURL)'],
        ['wget <url>', isTR ? 'Web sayfasını indir / görüntüle (Wget)' : 'Download / view web page (Wget)'],
        ['hostname', isTR ? 'Bilgisayar adı' : 'Computer name'],
        ['dir', isTR ? 'Dosya listesi' : 'Directory listing'],
        ['type <file>', isTR ? 'Dosya içeriğini görüntüle' : 'Display file content'],
        ['copy <src> <dest>', isTR ? 'Dosya kopyala' : 'Copy file'],
        ['move <src> <dest>', isTR ? 'Dosya/klasör taşı' : 'Move file or directory'],
        ['ren <old> <new>', isTR ? 'Yeniden adlandır' : 'Rename file or directory'],
        ['ver', isTR ? 'Versiyon bilgisi' : 'Version info'],
        ['cls', isTR ? 'Ekranı temizle' : 'Clear screen'],
        ['help / ?', isTR ? 'PC komut yardımı' : 'Desktop command help'],
      ]
    },
    {
      id: 'python-commands',
      icon: Terminal,
      title: isTR ? 'Python Yorumlayıcısı & Komutlar' : 'Python Interpreter & Commands',
      type: 'commands',
      cmds: [
        ['python <script.py> [args]', isTR ? 'Python betik dosyasını çalıştır' : 'Run Python script file'],
        ['python -c "<code>"', isTR ? 'Tek satırlık Python kodu çalıştır' : 'Execute inline Python code'],
        ['python', isTR ? 'İnteraktif Python kabuğunu (REPL) başlat' : 'Start interactive Python REPL shell'],
        ['print(value, ...)', isTR ? 'Ekrana metin/değer yazdır' : 'Print text/value to stdout'],
        ['input([prompt])', isTR ? 'Kullanıcıdan metin girdisi oku' : 'Read input from user'],
        ['len(sequence)', isTR ? 'Dizi/liste/metin uzunluğunu al' : 'Get sequence/list/string length'],
        ['type(object)', isTR ? 'Nesnenin veri tipini döndür' : 'Return data type of object'],
        ['range([start], stop, [step])', isTR ? 'Sayı dizisi üretecini oluştur' : 'Create sequence generator'],
        ['int() / float() / str() / bool()', isTR ? 'Veri tipi dönüştürme fonksiyonları' : 'Data type casting functions'],
        ['list() / dict() / set() / tuple()', isTR ? 'Koleksiyon dönüştürme fonksiyonları' : 'Collection casting functions'],
        ['sum() / min() / max() / abs()', isTR ? 'Matematiksel dâhilî fonksiyonlar' : 'Built-in math utility functions'],
        ['sorted(iterable) / reversed(seq)', isTR ? 'Sıralama ve tersine çevirme' : 'Sorting and reversing iterables'],
        ['import json / math / sys / os / socket', isTR ? 'Dâhilî Python modüllerini içe aktar' : 'Import built-in Python modules'],
        ['exit() / quit()', isTR ? 'İnteraktif REPL kabuğundan çık' : 'Exit interactive REPL shell'],
      ]
    },
    {
      id: 'knowledge-python',
      icon: FileText,
      title: isTR ? 'Bilgi: Python Yorumlayıcısı Nedir?' : 'Knowledge: What is Python Engine?',
      type: 'info',
      cmds: [
        ['Python 3 Engine', isTR ? 'NetworkSimulator PC cihazlarında yerleşik tam teşekküllü bir Python 3 yorumlayıcısı bulunur. CMD terminalinden "python script.py" yazarak veya Dosya Düzenleyici üzerindeki "Çalıştır" butonuyla betiklerinizi çalıştırabilirsiniz. Nesne Yönelimli Programlama (OOP), Decorator\'lar, Generator\'lar (yield), Hata Yakalama (try/except) ve ağ soket simülasyonu (socket, json, requests) tam desteklenir.' : 'NetworkSimulator PC devices feature an integrated Python 3 engine. You can execute scripts via CMD using "python script.py" or via the File Editor "Run" button. OOP (classes/inheritance), Decorators, Generators (yield), Exception handling (try/except), and network socket simulation (socket, json, requests) are fully supported.'],
      ]
    },
    {
      id: 'network-terms',
      icon: Book,
      title: isTR ? 'Ağ Terimleri' : 'Network Terms',
      type: 'info',
      cmds: [
        ['IP Address', isTR ? 'Ağda cihazı tanımlayan benzersiz sayısal adres (örn: 192.168.1.1)' : 'Unique numerical address identifying a device on a network (e.g., 192.168.1.1)'],
        ['MAC Address', isTR ? 'Ağ kartının fiziksel adresi, 48-bit onaltılı format (örn: 00-1a-2b-3c-4d-5e)' : 'Physical address of network interface, 48-bit hex format (e.g., 00-1a-2b-3c-4d-5e)'],
        ['Gateway', isTR ? 'Farklı ağlara erişim sağlayan cihaz, genellikle router' : 'Device providing access to other networks, typically a router'],
        ['Subnet Mask', isTR ? 'IP adresinin ağ ve host kısımlarını ayıran sayı (örn: 255.255.255.0)' : 'Separates network and host portions of IP address (e.g., 255.255.255.0)'],
        ['Router', isTR ? 'Ağlar arasında veri yönlendiren cihaz' : 'Device that routes data between networks'],
        ['Switch', isTR ? 'Yerel ağda cihazları birbirine bağlayan cihaz' : 'Device connecting devices within local network'],
        ['Firewall', isTR ? 'Yetkisiz ağ erişimini engelleyen güvenlik sistemi' : 'Security system blocking unauthorized network access'],
        ['Port', isTR ? 'Hizmet ve protokolleri tanımlayan sayısal kimlik (SSH: 22, HTTP: 80, HTTPS: 443)' : 'Numerical identifier for services (SSH: 22, HTTP: 80, HTTPS: 443)'],
        ['Protocol', isTR ? 'Ağ iletişimi için kuralları tanımlayan standart' : 'Standard defining rules for network communication'],
        ['Bandwidth', isTR ? 'Ağ bağlantısının saniye cinsinden veri aktarım kapasitesi (Mbps, Gbps)' : 'Network link capacity measured in data transfer per second (Mbps, Gbps)'],
        ['Ping', isTR ? 'Cihazlar arasındaki iletişim hızı, milisaniye cinsinden' : 'Communication speed between devices, measured in milliseconds'],
        ['Packet', isTR ? 'Ağda iletilen veri biriminin adı' : 'Unit of data transmitted over network'],
        ['VLAN', isTR ? 'Fiziksel ağı mantıksal gruplara bölen sistem' : 'System partitioning physical network into logical groups'],
        ['Proxy', isTR ? 'İstemci ile sunucu arasında aracı görev yapan sunucu' : 'Server acting as intermediary between client and server'],
        ['VPN', isTR ? 'İnternet üzerinden güvenli ve şifreli bağlantı' : 'Secure encrypted connection over the internet'],
        ['Default Gateway', isTR ? 'Yerel ağ dışındaki hedeflere gönderim yapan varsayılan yönlendirici' : 'Router used as the next hop for destinations outside the local network'],
        ['Broadcast Domain', isTR ? 'Yayın paketlerinin ulaşabildiği mantıksal ağ alanı; VLAN’lar yayın alanını böler' : 'Logical area reached by broadcast traffic; VLANs split broadcast domains'],
        ['Collision Domain', isTR ? 'Ethernet çarpışmalarının oluşabildiği ortak bölüm; modern switch portları bunu ayırır' : 'Shared Ethernet segment where collisions can occur; switch ports isolate it'],
        ['Subnet', isTR ? 'Daha büyük bir IP ağının, subnet mask ile ayrılmış alt ağı' : 'A smaller IP network carved from a larger network by a subnet mask'],
        ['CIDR', isTR ? 'Ağ önekini /24 gibi önek uzunluğuyla gösteren sınıfsız adresleme yöntemi' : 'Classless addressing notation that expresses a prefix length such as /24'],
        ['Unicast / Multicast / Broadcast', isTR ? 'Sırasıyla tek hedefe, seçili alıcılara ve aynı ağdaki tüm alıcılara gönderim' : 'Traffic sent to one destination, a subscribed group, or all hosts on a local segment'],
        ['Access Port', isTR ? 'Genellikle tek bir VLAN’a ait uç cihaz switch portu' : 'Edge switch port that normally carries one access VLAN'],
        ['Trunk Port', isTR ? 'Birden fazla VLAN’ı 802.1Q etiketleriyle taşıyan bağlantı portu' : 'Link port that carries multiple VLANs using 802.1Q tags'],
        ['Native VLAN', isTR ? '802.1Q trunk üzerinde etiketsiz taşınan VLAN' : 'VLAN carried untagged across an 802.1Q trunk'],
        ['Routing Table', isTR ? 'Hedef ağ, next-hop ve çıkış arayüzü bilgilerini tutan yönlendirme tablosu' : 'Table containing destination networks, next hops, and outgoing interfaces'],
        ['Next Hop', isTR ? 'Paketi hedef ağa yaklaştıran bir sonraki router adresi' : 'The next router address used to move a packet toward its destination'],
        ['Metric', isTR ? 'Yönlendirme protokolünün yolları karşılaştırmak için kullandığı maliyet değeri' : 'Cost used by a routing protocol to compare candidate paths'],
        ['Convergence', isTR ? 'Yönlendiricilerin ağ değişikliğinden sonra ortak topoloji bilgisine ulaşması' : 'Process by which routers reach a consistent view after a topology change'],
        ['Latency', isTR ? 'Paketin kaynaktan hedefe ulaşması için geçen süre (ms)' : 'Time required for a packet to travel from source to destination (ms)'],
        ['Jitter', isTR ? 'Ardışık paketlerin gecikme değerlerindeki değişim; ses/video için kritiktir' : 'Variation in packet delay; especially important for voice and video'],
        ['Packet Loss', isTR ? 'Gönderilen paketlerin hedefe ulaşmayan oranı' : 'Percentage of transmitted packets that do not reach the destination'],
        ['Duplex', isTR ? 'Bağlantının tek yönlü (half) veya çift yönlü (full) çalışma biçimi' : 'Whether a link operates half-duplex or full-duplex'],
        ['PoE', isTR ? 'Ethernet kablosu üzerinden veriyle birlikte elektrik sağlama' : 'Supplying electrical power over the same Ethernet cable as data'],
        ['FHRP', isTR ? 'HSRP/VRRP gibi, yedekli varsayılan ağ geçidi sağlayan protokoller ailesi' : 'Protocol family such as HSRP/VRRP that provides a redundant default gateway'],
        ['DHCP Relay', isTR ? 'DHCP yayınlarını farklı bir IP ağına DHCP sunucusuna iletme işlevi' : 'Forwarding DHCP broadcasts to a server on another IP network'],
        ['ACL', isTR ? 'Trafiği kaynak, hedef, protokol veya port koşullarına göre izinleyen/engelleyen kural listesi' : 'Rules that permit or deny traffic by source, destination, protocol, or port'],
        ['NAT / PAT', isTR ? 'IP adreslerini; PAT ise aynı genel IP üzerinde portları dönüştürür' : 'NAT translates IP addresses; PAT also multiplexes many hosts through ports'],
        ['QoS Queue', isTR ? 'Çıkış kapasitesi yetmediğinde paketlerin öncelik ve bant genişliğine göre beklediği kuyruk' : 'Egress queue where packets wait according to priority and bandwidth policy'],
        ['LLDP', isTR ? 'Komşu cihaz ve port bilgilerini keşfetmek için kullanılan standart katman-2 protokolü' : 'Standards-based Layer-2 protocol for discovering neighboring devices and ports'],
        ['EAPOL', isTR ? '802.1X kimlik doğrulama mesajlarını Ethernet üzerinde taşıyan çerçeve' : 'Ethernet frame used to carry 802.1X authentication messages'],
        ['RADIUS', isTR ? 'Merkezi kimlik doğrulama, yetkilendirme ve hesaplama (AAA) protokolü' : 'Centralized authentication, authorization, and accounting (AAA) protocol'],
        ['ESP', isTR ? 'IPsec’in veri gizliliği ve bütünlüğü sağlayan Encapsulating Security Payload bileşeni' : 'IPsec Encapsulating Security Payload providing confidentiality and integrity'],
        ['Overlay / Underlay', isTR ? 'Overlay mantıksal sanal ağdır; underlay onu taşıyan fiziksel/IP altyapıdır' : 'Overlay is the logical virtual network; underlay is the physical/IP transport beneath it'],
      ]
    },
    {
      id: 'abbreviations',
      icon: Zap,
      title: isTR ? 'Ağ Kısaltmaları' : 'Network Abbreviations',
      type: 'info',
      cmds: [
        ['DHCP', isTR ? 'Dynamic Host Configuration Protocol - IP adreslerini otomatik olarak atayan protokol' : 'Dynamic Host Configuration Protocol - automatically assigns IP addresses'],
        ['DNS', isTR ? 'Domain Name System - Alan adlarını IP adreslerine çeviren sistem' : 'Domain Name System - converts domain names to IP addresses'],
        ['ARP', isTR ? 'Address Resolution Protocol - IP adresini MAC adresine çeviren protokol' : 'Address Resolution Protocol - converts IP to MAC address'],
        ['TCP', isTR ? 'Transmission Control Protocol - Güvenilir, bağlantı tabanlı protokol' : 'Transmission Control Protocol - reliable, connection-based protocol'],
        ['UDP', isTR ? 'User Datagram Protocol - Hızlı, bağlantısız protokol' : 'User Datagram Protocol - fast, connectionless protocol'],
        ['SSH', isTR ? 'Secure Shell - Güvenli uzak bağlantı protokolü' : 'Secure Shell - secure remote connection protocol'],
        ['HTTP', isTR ? 'HyperText Transfer Protocol - Web sayfaları için protokol' : 'HyperText Transfer Protocol - protocol for web pages'],
        ['HTTPS', isTR ? 'HTTP Secure - şifreli HTTP protokolü' : 'HTTP Secure - encrypted HTTP protocol'],
        ['FTP', isTR ? 'File Transfer Protocol - Dosya aktarımı protokolü' : 'File Transfer Protocol - file transfer protocol'],
        ['SFTP', isTR ? 'SSH File Transfer Protocol - Güvenli dosya aktarımı' : 'SSH File Transfer Protocol - secure file transfer'],
        ['SMTP', isTR ? 'Simple Mail Transfer Protocol - E-posta gönderme protokolü' : 'Simple Mail Transfer Protocol - email sending protocol'],
        ['POP3', isTR ? 'Post Office Protocol 3 - E-posta alma protokolü' : 'Post Office Protocol 3 - email receiving protocol'],
        ['IMAP', isTR ? 'Internet Message Access Protocol - E-posta yönetimi protokolü' : 'Internet Message Access Protocol - email management protocol'],
        ['QoS', isTR ? 'Quality of Service - Hizmet Kalitesi' : 'Quality of Service - network traffic priority'],
        ['MTU', isTR ? 'Maximum Transmission Unit - Maksimum Aktarım Birimi' : 'Maximum Transmission Unit - maximum packet size'],
        ['RFC', isTR ? 'Request for Comments - İnternet standartlarını tanımlayan dokümanlardır' : 'Request for Comments - internet standard documentation'],
        ['CIDR', isTR ? 'Classless Inter-Domain Routing - IP blokları gösterim yöntemi' : 'Classless Inter-Domain Routing - IP notation method'],
        ['ICMP', isTR ? 'Internet Control Message Protocol - Ağ diagnostik protokolü' : 'Internet Control Message Protocol - network diagnostic protocol'],
        ['MAC', isTR ? 'Media Access Control - Ağ kartının fiziksel adresi, 48-bit onaltılı format (örn: 00-1a-2b-3c-4d-5e)' : 'Media Access Control - physical address of network interface, 48-bit hex format (e.g., 00-1a-2b-3c-4d-5e)'],
        ['IP', isTR ? 'Internet Protocol - Ağda cihazı tanımlayan benzersiz sayısal adres (örn: 192.168.1.1)' : 'Internet Protocol - unique numerical address identifying a device on a network (e.g., 192.168.1.1)'],
        ['NAT', isTR ? 'Network Address Translation - Ağ adresi dönüştürme' : 'Network Address Translation - translates private IPs to public'],
        ['ACL', isTR ? 'Access Control List - Erişim kontrol listesi' : 'Access Control List - filters network traffic'],
        ['VPN', isTR ? 'Virtual Private Network - İnternet üzerinden güvenli ve şifreli bağlantı' : 'Virtual Private Network - secure encrypted connection over the internet'],
        ['WLAN', isTR ? 'Wireless Local Area Network - Kablosuz yerel ağ' : 'Wireless Local Area Network - wireless local network'],
        ['SSID', isTR ? 'Service Set Identifier - Kablosuz ağ adı' : 'Service Set Identifier - wireless network name'],
        ['STP', isTR ? 'Spanning Tree Protocol - Ağ halkalarını önleyen protokol' : 'Spanning Tree Protocol - prevents network loops'],
        ['OSPF', isTR ? 'Open Shortest Path First - Dinamik yönlendirme protokolü' : 'Open Shortest Path First - dynamic routing protocol'],
        ['RIP', isTR ? 'Routing Information Protocol - Basit yönlendirme protokolü' : 'Routing Information Protocol - basic routing protocol'],
        ['BGP', isTR ? 'Border Gateway Protocol - InterASA yönlendirme protokolü' : 'Border Gateway Protocol - inter-AS routing protocol'],
        ['SNMP', isTR ? 'Simple Network Management Protocol - Ağ yönetim protokolü' : 'Simple Network Management Protocol - network management protocol'],
        ['NTP', isTR ? 'Network Time Protocol - Ağ zaman senkronizasyon' : 'Network Time Protocol - network time synchronization'],
        ['LDAP', isTR ? 'Lightweight Directory Access Protocol - Kullanıcı dizin hizmeti' : 'Lightweight Directory Access Protocol - directory service protocol'],
        ['SSL/TLS', isTR ? 'Secure Socket Layer / Transport Layer Security - şifreleme protokolü' : 'Secure Socket Layer / Transport Layer Security - encryption protocol'],
        ['L2TP', isTR ? 'Layer 2 Tunneling Protocol - Tünel oluşturma protokolü' : 'Layer 2 Tunneling Protocol - tunneling protocol'],
        ['GRE', isTR ? 'Generic Routing Encapsulation - Jenerik yönlendirme protokolü' : 'Generic Routing Encapsulation - generic tunneling protocol'],
        ['LAN', isTR ? 'Local Area Network - Yerel alan ağı' : 'Local Area Network - local network'],
        ['WAN', isTR ? 'Wide Area Network - Geniş alan ağı' : 'Wide Area Network - geographically distributed network'],
        ['OSI', isTR ? 'Open Systems Interconnection - Yedi katmanlı referans modeli' : 'Open Systems Interconnection - seven-layer reference model'],
        ['TCP/IP', isTR ? 'Transmission Control Protocol / Internet Protocol - İnternet protokol ailesi' : 'Transmission Control Protocol / Internet Protocol - Internet protocol suite'],
        ['VLSM', isTR ? 'Variable Length Subnet Mask - Değişken uzunluklu alt ağ maskesi' : 'Variable Length Subnet Mask - variable-size subnetting'],
        ['FHRP', isTR ? 'First Hop Redundancy Protocol - Yedekli ilk atlama/ağ geçidi protokolü' : 'First Hop Redundancy Protocol - redundant first-hop gateway protocol'],
        ['HSRP', isTR ? 'Hot Standby Router Protocol - varsayılan ağ geçidi yedekliliği' : 'Hot Standby Router Protocol - first-hop gateway redundancy'],
        ['VRRP', isTR ? 'Virtual Router Redundancy Protocol - Standart sanal router yedekliliği' : 'Virtual Router Redundancy Protocol - standards-based virtual router redundancy'],
        ['PAT', isTR ? 'Port Address Translation - Çoklu hostu portlarla tek genel IP üzerinden taşır' : 'Port Address Translation - multiplexes hosts through one public IP using ports'],
        ['RSTP', isTR ? 'Rapid Spanning Tree Protocol - Daha hızlı STP yakınsaması' : 'Rapid Spanning Tree Protocol - faster STP convergence'],
        ['MSTP', isTR ? 'Multiple Spanning Tree Protocol - VLAN gruplarını birden çok STP örneğine eşler' : 'Multiple Spanning Tree Protocol - maps VLAN groups to multiple STP instances'],
        ['LLDP-MED', isTR ? 'LLDP Media Endpoint Discovery - IP telefon ve medya uç noktası keşfi' : 'LLDP Media Endpoint Discovery - discovery for phones and media endpoints'],
        ['EAPOL', isTR ? 'Extensible Authentication Protocol over LAN - 802.1X Ethernet kimlik doğrulama çerçevesi' : 'Extensible Authentication Protocol over LAN - 802.1X Ethernet authentication frames'],
        ['AAA', isTR ? 'Authentication, Authorization, Accounting - Kimlik doğrulama, yetkilendirme ve hesaplama' : 'Authentication, Authorization, Accounting - identity, permission, and audit functions'],
        ['RADIUS', isTR ? 'Remote Authentication Dial-In User Service - AAA ve 802.1X kimlik doğrulama sunucusu' : 'Remote Authentication Dial-In User Service - AAA and 802.1X authentication service'],
        ['TACACS+', isTR ? 'Terminal Access Controller Access-Control System Plus - Yönetim erişimi için AAA protokolü' : 'Terminal Access Controller Access-Control System Plus - AAA protocol for administrative access'],
        ['IPsec', isTR ? 'Internet Protocol Security - IP katmanında güvenli iletişim paketi' : 'Internet Protocol Security - secure communication at the IP layer'],
        ['ESP', isTR ? 'Encapsulating Security Payload - IPsec veri kapsülleme ve şifreleme bileşeni' : 'Encapsulating Security Payload - IPsec payload encapsulation and encryption component'],
        ['IKE', isTR ? 'Internet Key Exchange - IPsec güvenlik ilişkisinin anahtar değişim protokolü' : 'Internet Key Exchange - key exchange protocol for IPsec security associations'],
        ['MSS', isTR ? 'Maximum Segment Size - TCP veri bölümünün en büyük boyutu' : 'Maximum Segment Size - largest TCP payload segment size'],
        ['DSCP', isTR ? 'Differentiated Services Code Point - IP başlığında QoS sınıflandırma değeri' : 'Differentiated Services Code Point - QoS classification value in the IP header'],
        ['LLQ', isTR ? 'Low Latency Queuing - Öncelikli, düşük gecikmeli kuyruklama' : 'Low Latency Queuing - strict priority queue for low latency'],
        ['CBWFQ', isTR ? 'Class-Based Weighted Fair Queuing - Sınıf tabanlı ağırlıklı adil kuyruklama' : 'Class-Based Weighted Fair Queuing - class-based weighted fair scheduling'],
        ['WFQ', isTR ? 'Weighted Fair Queuing - Ağırlıklı adil kuyruklama' : 'Weighted Fair Queuing - weighted fair scheduling'],
        ['SLA', isTR ? 'Service Level Agreement - Hizmet düzeyi taahhüdü; IP SLA ölçümleriyle izlenebilir' : 'Service Level Agreement - service target measurable with IP SLA probes'],
        ['IP SLA', isTR ? 'IP Service Level Agreement - Sentetik trafikle gecikme, jitter ve erişilebilirlik ölçümü' : 'IP Service Level Agreement - synthetic measurement of latency, jitter, and reachability'],
        ['SDN', isTR ? 'Software-Defined Networking - Kontrol düzlemini yazılımla merkezileştiren yaklaşım' : 'Software-Defined Networking - approach that centralizes control in software'],
        ['YANG', isTR ? 'Yet Another Next Generation - Ağ yapılandırma/veri modelleri için dil' : 'Yet Another Next Generation - language for network configuration and data models'],
        ['NETCONF', isTR ? 'Network Configuration Protocol - YANG verisini güvenli RPC ile yönetme protokolü' : 'Network Configuration Protocol - secure RPC protocol for managing YANG data'],
        ['RESTCONF', isTR ? 'RESTful Configuration Protocol - YANG kaynaklarına HTTP/REST erişimi' : 'RESTful Configuration Protocol - HTTP/REST access to YANG resources'],
        ['API', isTR ? 'Application Programming Interface - Uygulamaların birbirleriyle iletişim arayüzü' : 'Application Programming Interface - interface through which software systems communicate'],
        ['NBI / SBI', isTR ? 'Northbound/Southbound Interface - Controller’ın uygulama ve altyapı yönündeki arayüzleri' : 'Northbound/Southbound Interface - controller interfaces toward applications and infrastructure'],
      ]
    },
  ];
}
