import { Terminal, Globe, Wifi, Settings, Eye, Server, Router, Network, LucideIcon } from 'lucide-react';

export interface CommandDefinition {
  id: string;
  icon: LucideIcon;
  title: string;
  cmds: [string, string][];
}

export function getCommandCategories(isTR: boolean): CommandDefinition[] {
  return [
    {
      id: 'system',
      icon: Terminal,
      title: isTR ? 'Sistem & Oturum' : 'System & Session',
      cmds: [
        ['enable', isTR ? 'Ayrıcalıklı moda geç' : 'Enter privileged mode'],
        ['disable', isTR ? 'Kullanıcı moduna dön' : 'Return to user mode'],
        ['configure terminal', isTR ? 'Yapılandırma modu' : 'Enter config mode'],
        ['exit', isTR ? 'Moddan çık' : 'Exit current mode'],
        ['end', isTR ? 'Ayrıcalıklı moda dön' : 'Return to privileged'],
        ['help', isTR ? 'Yardım sistemini göster' : 'Display help system'],
      ]
    },
    {
      id: 'privileged',
      icon: Server,
      title: isTR ? 'Privileged EXEC' : 'Privileged EXEC',
      cmds: [
        ['ping <host> [s] [c]', isTR ? 'Bağlantı testi (ICMP)' : 'Ping host (ICMP)'],
        ['traceroute <host>', isTR ? 'Rota izleme (Unix)' : 'Trace route (Unix)'],
        ['tracert <host>', isTR ? 'Rota izleme (Windows)' : 'Trace route (Windows)'],
        ['telnet <host> [port]', isTR ? 'Telnet bağlantısı' : 'Telnet connection'],
        ['ssh [-l user] <host>', isTR ? 'SSH bağlantısı' : 'SSH connection'],
        ['write memory', isTR ? 'Yapılandırmayı kaydet' : 'Save configuration'],
        ['copy run start', isTR ? 'Yapılandırmayı kaydet' : 'Save configuration'],
        ['erase startup-config', isTR ? 'Startup config sil' : 'Erase startup config'],
        ['erase nvram', isTR ? 'NVRAM dosya sistemini sil' : 'Erase NVRAM'],
        ['reload', isTR ? 'Cihazı yeniden yükle' : 'Reload device'],
        ['ip route <n> <mask> <h>', isTR ? 'Statik rota ekle' : 'Add static route'],
        ['no ip route <n> <mask> <h>', isTR ? 'Statik rotayı sil' : 'Remove static route'],
        ['debug <type>', isTR ? 'Hata ayıklamayı aç' : 'Enable debugging'],
        ['undebug all', isTR ? 'Tüm hataları kapat' : 'Disable all debugging'],
        ['terminal length <0-512>', isTR ? 'Terminal satırı' : 'Set terminal length'],
        ['clear arp-cache', isTR ? 'ARP önbelleğini sil' : 'Clear ARP cache'],
        ['clear mac address-table', isTR ? 'MAC tablosunu sil' : 'Clear MAC table'],
        ['clear counters', isTR ? 'Sayaçları sıfırla' : 'Clear counters'],
        ['do <command>', isTR ? 'Privileged komut çalıştır' : 'Execute privileged cmd'],
      ]
    },
    {
      id: 'global',
      icon: Globe,
      title: isTR ? 'Global Yapılandırma' : 'Global Config',
      cmds: [
        ['hostname <name>', isTR ? 'Cihaz adı' : 'Set hostname'],
        ['vlan <id>', isTR ? 'VLAN oluştur' : 'Create VLAN'],
        ['no vlan <id>', isTR ? 'VLAN sil' : 'Delete VLAN'],
        ['name <name>', isTR ? 'VLAN adı (vlan modunda)' : 'Set VLAN name'],
        ['interface <name>', isTR ? 'Arayüz seç' : 'Select interface'],
        ['interface range <r>', isTR ? 'Arayüz aralığı' : 'Interface range'],
        ['no interface vlan <id>', isTR ? 'VLAN arayüzünü sil' : 'Delete VLAN interface'],
        ['ip routing', isTR ? 'IP yönlendirme (L3)' : 'Enable IP routing (L3)'],
        ['no ip routing', isTR ? 'IP yönlendirmeyi kapat' : 'Disable IP routing'],
        ['ip default-gateway <ip>', isTR ? 'Varsayılan ağ geçidi' : 'Set default gateway'],
        ['ip domain-name <name>', isTR ? 'Alan adı' : 'Set domain name'],
        ['no ip domain lookup', isTR ? 'DNS aramayı kapat' : 'Disable DNS lookup'],
        ['ip http server', isTR ? 'HTTP sunucusunu aç' : 'Enable HTTP server'],
        ['no ip http server', isTR ? 'HTTP sunucusunu kapat' : 'Disable HTTP server'],
        ['ip ssh version {1|2}', isTR ? 'SSH versiyonu' : 'Set SSH version'],
        ['ip dhcp snooping', isTR ? 'DHCP snooping aç' : 'Enable DHCP snooping'],
        ['service password-enc', isTR ? 'Şifreleri şifrele' : 'Encrypt passwords'],
        ['enable secret <pass>', isTR ? 'Enable secret' : 'Set enable secret'],
        ['enable password <pass>', isTR ? 'Enable password' : 'Set enable password'],
        ['banner motd #<msg>#', isTR ? 'MOTD banner' : 'MOTD banner'],
        ['banner login #<msg>#', isTR ? 'Login banner' : 'Login banner'],
        ['no banner {motd|login}', isTR ? 'Banner sil' : 'Remove banner'],
        ['vtp mode {server|client}', isTR ? 'VTP modu' : 'Set VTP mode'],
        ['vtp domain <name>', isTR ? 'VTP domain' : 'Set VTP domain'],
        ['spanning-tree mode {m}', isTR ? 'STP modu' : 'Set STP mode'],
        ['no spanning-tree', isTR ? 'STP\'yi kapat' : 'Disable spanning-tree'],
        ['username <n> pass <p>', isTR ? 'Kullanıcı oluştur' : 'Create user'],
        ['no username <name>', isTR ? 'Kullanıcıyı sil' : 'Remove user'],
        ['cdp run', isTR ? 'CDP\'yi aç' : 'Enable CDP globally'],
        ['mls qos', isTR ? 'QoS\'u aç' : 'Enable MLS QoS'],
        ['ip dhcp pool <name>', isTR ? 'DHCP havuzu' : 'Create DHCP pool'],
        ['no ip dhcp pool <name>', isTR ? 'DHCP havuzunu sil' : 'Remove DHCP pool'],
        ['ip dhcp excluded <ip>', isTR ? 'DHCP hariç tut' : 'Exclude DHCP addr'],
        ['ntp server <ip>', isTR ? 'NTP sunucusu' : 'Set NTP server'],
        ['clock timezone <n> <o>', isTR ? 'Zaman dilimi' : 'Set timezone'],
        ['ip name-server <ip>', isTR ? 'DNS sunucusu' : 'Set DNS server'],
        ['system mtu <size>', isTR ? 'Sistem MTU' : 'Set system MTU'],
        ['errdisable recovery', isTR ? 'Hata kurtarma' : 'Errdisable recovery'],
        ['spanning-tree portfast default', isTR ? 'Global PortFast' : 'Global PortFast'],
      ]
    },
    {
      id: 'interface',
      icon: Settings,
      title: isTR ? 'Arayüz Yapılandırması' : 'Interface Config',
      cmds: [
        ['shutdown', isTR ? 'Arayüzü kapat' : 'Disable interface'],
        ['no shutdown', isTR ? 'Arayüzü aç' : 'Enable interface'],
        ['speed {10|100|1000|auto}', isTR ? 'Hız ayarla' : 'Set speed'],
        ['duplex {half|full|auto}', isTR ? 'Duplex ayarla' : 'Set duplex'],
        ['description <text>', isTR ? 'Arayüz açıklaması' : 'Set description'],
        ['no description', isTR ? 'Açıklamayı sil' : 'Clear description'],
        ['switchport mode access', isTR ? 'Erişim modu' : 'Access mode'],
        ['switchport mode trunk', isTR ? 'Trunk modu' : 'Trunk mode'],
        ['switchport mode dynamic {m}', isTR ? 'DTP modu' : 'Set DTP mode'],
        ['no switchport mode', isTR ? 'Modu sıfırla' : 'Reset switchport mode'],
        ['switchport access vlan <id>', isTR ? 'VLAN ata' : 'Assign VLAN'],
        ['no switchport access vlan', isTR ? 'VLAN atamasını sil' : 'Remove VLAN assign'],
        ['switchport trunk native <id>', isTR ? 'Native VLAN' : 'Set native VLAN'],
        ['switchport trunk allowed <l>', isTR ? 'İzinli VLANlar' : 'Set allowed VLANs'],
        ['switchport nonegotiate', isTR ? 'DTP\'yi kapat' : 'Disable DTP'],
        ['switchport voice vlan <id>', isTR ? 'Ses VLAN\'ı' : 'Set voice VLAN'],
        ['switchport port-security', isTR ? 'Port güvenliği' : 'Port security'],
        ['switchport port-security max <n>', isTR ? 'Maksimum MAC' : 'Set max MACs'],
        ['switchport port-security violation {a}', isTR ? 'İhlal aksiyonu' : 'Violation action'],
        ['switchport port-security sticky', isTR ? 'Sticky MAC' : 'Enable sticky MAC'],
        ['no switchport port-security', isTR ? 'Güvenliği kapat' : 'Disable port security'],
        ['no switchport', isTR ? 'L3 portuna dönüştür' : 'Convert to L3 port'],
        ['spanning-tree portfast', isTR ? 'PortFast aç' : 'Enable PortFast'],
        ['spanning-tree bpduguard {e|d}', isTR ? 'BPDU Guard' : 'BPDU Guard'],
        ['spanning-tree cost <cost>', isTR ? 'STP maliyeti' : 'Set STP cost'],
        ['spanning-tree priority <p>', isTR ? 'STP önceliği' : 'Set STP priority'],
        ['ip address <ip> <mask>', isTR ? 'IP adresi ata' : 'Set IP address'],
        ['no ip address', isTR ? 'IP adresini sil' : 'Remove IP address'],
        ['ip helper-address <ip>', isTR ? 'DHCP relay' : 'Set DHCP relay'],
        ['no ip helper-address', isTR ? 'DHCP relay sil' : 'Remove DHCP relay'],
        ['cdp enable', isTR ? 'CDP\'yi aç (arayüz)' : 'Enable CDP (interface)'],
        ['channel-group <n> mode', isTR ? 'EtherChannel' : 'EtherChannel'],
        ['no channel-group', isTR ? 'EtherChannel sil' : 'Remove from channel'],
        ['access-list <acl>', isTR ? 'Erişim listesi' : 'Apply access list'],
        ['monitor session <n>', isTR ? 'SPAN/RSPAN' : 'Configure SPAN/RSPAN'],
      ]
    },
    {
      id: 'wireless',
      icon: Wifi,
      title: isTR ? 'Kablosuz (WiFi)' : 'Wireless (WiFi)',
      cmds: [
        ['ssid <name>', isTR ? 'Ağ adı (SSID)' : 'Set network name'],
        ['encryption {open|wpa2|wpa3}', isTR ? 'Güvenlik tipi' : 'Security type'],
        ['wifi-password <pass>', isTR ? 'WiFi şifresi' : 'WiFi password'],
        ['wifi-channel {band}', isTR ? 'WiFi bandı' : 'Set WiFi band'],
        ['wifi-mode {ap|client}', isTR ? 'WiFi modu' : 'WiFi mode'],
      ]
    },
    {
      id: 'line',
      icon: Router,
      title: isTR ? 'Hat Yapılandırması' : 'Line Config',
      cmds: [
        ['line console 0', isTR ? 'Konsol hattı' : 'Console line'],
        ['line vty 0 4', isTR ? 'VTY hatları' : 'VTY lines'],
        ['password <pass>', isTR ? 'Şifre ayarla' : 'Set password'],
        ['no password', isTR ? 'Şifreyi sil' : 'Remove password'],
        ['login', isTR ? 'Giriş kontrolü' : 'Enable login'],
        ['no login', isTR ? 'Giriş kontrolü kapat' : 'Disable login'],
        ['transport input {p}', isTR ? 'Giriş protokolleri' : 'Input protocols'],
        ['no transport input', isTR ? 'Girişleri sıfırla' : 'Reset transport input'],
        ['logging synchronous', isTR ? 'Senkron loglama' : 'Sync logging'],
        ['no logging synchronous', isTR ? 'Senkron log kapat' : 'Disable sync logging'],
        ['exec-timeout <m> [s]', isTR ? 'Zaman aşımı' : 'Exec timeout'],
        ['no exec-timeout', isTR ? 'Zaman aşımı sıfırla' : 'Reset exec timeout'],
        ['history size <n>', isTR ? 'Geçmiş boyutu' : 'Set history size'],
        ['autocommand <cmd>', isTR ? 'Otomatik komut' : 'Set auto-command'],
        ['privilege level <0-15>', isTR ? 'Yetki seviyesi' : 'Set privilege level'],
      ]
    },
    {
      id: 'router',
      icon: Network,
      title: isTR ? 'Yönlendirme (Routing)' : 'Routing Config',
      cmds: [
        ['router rip', isTR ? 'RIP yönlendirmesi' : 'Enable RIP'],
        ['router ospf [<id>]', isTR ? 'OSPF yönlendirmesi' : 'Enable OSPF'],
        ['no router {rip|ospf}', isTR ? 'Yönlendirmeyi kapat' : 'Disable routing'],
        ['network <ip> [wildcard]', isTR ? 'Ağ ekle' : 'Add network'],
        ['network <ip> area <id>', isTR ? 'OSPF ağı ekle' : 'Add OSPF network'],
        ['router-id <ip>', isTR ? 'Router ID ayarla' : 'Set router ID'],
        ['passive-interface <int>', isTR ? 'Pasif arayüz' : 'Passive interface'],
        ['default-info originate', isTR ? 'Varsayılan rota' : 'Default route'],
      ]
    },
    {
      id: 'dhcp',
      icon: Server,
      title: isTR ? 'DHCP Havuzu' : 'DHCP Pool Config',
      cmds: [
        ['network <net> <mask>', isTR ? 'Havuz ağı' : 'Pool network'],
        ['default-router <ip>', isTR ? 'Varsayılan geçit' : 'Default router'],
        ['dns-server <ip>', isTR ? 'DNS sunucusu' : 'DNS server'],
        ['lease {days|infinite}', isTR ? 'Kira süresi' : 'Lease duration'],
        ['domain-name <name>', isTR ? 'Alan adı' : 'Domain name'],
      ]
    },
    {
      id: 'show',
      icon: Eye,
      title: isTR ? 'Show Komutları' : 'Show Commands',
      cmds: [
        ['show', isTR ? 'Özet bilgi' : 'Display summary'],
        ['show running-config', isTR ? 'Çalışan yapılandırma' : 'Running config'],
        ['show startup-config', isTR ? 'Başlangıç yapılandırması' : 'Startup config'],
        ['show version', isTR ? 'Sistem bilgisi' : 'System version'],
        ['show interfaces', isTR ? 'Tüm arayüzler' : 'Display all interfaces'],
        ['show interfaces trunk', isTR ? 'Trunk arayüzler' : 'Display trunks'],
        ['show interface <name>', isTR ? 'Arayüz ayrıntısı' : 'Interface details'],
        ['show ip interface brief', isTR ? 'Arayüz özeti' : 'IP interface brief'],
        ['show vlan [brief]', isTR ? 'VLAN listesi' : 'VLAN list'],
        ['show mac address-table', isTR ? 'MAC tablosu' : 'MAC address table'],
        ['show cdp neighbors', isTR ? 'CDP komşuları' : 'CDP neighbors'],
        ['show ip route', isTR ? 'Yönlendirme tablosu' : 'Routing table'],
        ['show clock', isTR ? 'Sistem saati' : 'Display system clock'],
        ['show flash', isTR ? 'Flash içeriği' : 'Display flash'],
        ['show boot', isTR ? 'Boot bilgisi' : 'Display boot info'],
        ['show spanning-tree', isTR ? 'STP durumu' : 'STP status'],
        ['show port-security', isTR ? 'Port güvenliği' : 'Port security status'],
        ['show wireless', isTR ? 'Kablosuz durumu' : 'Display wireless status'],
        ['show ip dhcp snooping', isTR ? 'DHCP snooping' : 'Display DHCP snooping'],
        ['show ip dhcp pool', isTR ? 'DHCP havuzları' : 'Display DHCP pools'],
        ['show ip dhcp binding', isTR ? 'DHCP atamaları' : 'DHCP bindings'],
        ['show interfaces status', isTR ? 'Arayüz durumu' : 'Display port status'],
        ['show cdp', isTR ? 'CDP bilgisi' : 'Display CDP info'],
        ['show vtp status', isTR ? 'VTP durumu' : 'Display VTP status'],
        ['show etherchannel', isTR ? 'EtherChannel' : 'Display EtherChannel'],
        ['show arp', isTR ? 'ARP tablosu' : 'ARP table'],
        ['show mls qos', isTR ? 'QoS durumu' : 'Display QoS status'],
        ['show access-lists', isTR ? 'Erişim listeleri' : 'Display access lists'],
        ['show history', isTR ? 'Komut geçmişi' : 'Display command history'],
        ['show users', isTR ? 'Kullanıcılar' : 'Connected users'],
        ['show environment', isTR ? 'Donanım durumu' : 'Display hardware status'],
        ['show inventory', isTR ? 'Donanım envanteri' : 'Display inventory'],
        ['show errdisable recovery', isTR ? 'Hata kurtarma' : 'Display errdisable'],
        ['show debug', isTR ? 'Debug durumu' : 'Display debug status'],
        ['show processes', isTR ? 'İşlemler (CPU)' : 'Display processes'],
        ['show memory', isTR ? 'Bellek kullanımı' : 'Display memory usage'],
        ['show system mtu', isTR ? 'MTU ayarları' : 'Display MTU settings'],
      ]
    },
  ];
}
