// Helper: Generate prefixes for a command (e.g., 'telnet' -> 't','te','tel'...)
const pfx = (cmd: string, completions: string[], minLen = 1): Record<string, string[]> => {
  const result: Record<string, string[]> = {};
  for (let i = minLen; i <= cmd.length; i++) {
    result[cmd.slice(0, i)] = completions;
  }
  return result;
};

// Helper: Multi-prefix for ambiguous first letters (e.g., 't' -> ['telnet'])
const multi = (char: string, completions: string[]): Record<string, string[]> => {
  const result: Record<string, string[]> = { [char]: completions };
  completions.forEach(cmd => {
    for (let i = 1; i <= cmd.length; i++) {
      const prefix = cmd.slice(0, i);
      // Only add if this prefix is unique to this command
      const matches = completions.filter(c => c.startsWith(prefix));
      if (matches.length === 1) {
        result[char + prefix] = [cmd];
      }
    }
  });
  return result;
};

export const commandHelp: Record<string, Record<string, string[]>> = {
  'user': {
    '': ['enable', 'help', 'ping', 'show', 'telnet'],
    ...pfx('enable', ['enable']),
    ...pfx('help', ['help']),
    ...pfx('ping', ['ping']),
    ...multi('s', ['show', 'ssh']),
    ...pfx('show', ['arp', 'cdp', 'etherchannel', 'interface', 'interfaces', 'ip', 'ipv6', 'lldp', 'mac', 'spanning-tree', 'version', 'vlan']),
    'show cdp': ['neighbors'],
    'show cdp neighbors': ['detail'],
    'show lldp': ['neighbors'],
    'show lldp neighbors': ['detail'],
    'show interface': ['trunk'],
    'show interfaces': ['status', 'trunk'],
    'show ip': ['arp', 'eigrp', 'interface', 'nat', 'ospf', 'protocols', 'route', 'sla'],
    'show ip eigrp': ['neighbors'],
    'show ip sla': ['statistics'],
    'show ip interface': ['brief'],
    'show ip ospf': ['database', 'interface', 'neighbor'],
    'show ip nat': ['translations', 'statistics'],
    'show ipv6': ['dhcp', 'interface', 'neighbors', 'route'],
    'show ipv6 dhcp': ['pool'],
    'show ipv6 interface': ['brief'],
    'show mac': ['address-table'],
    'show vlan': ['brief'],
  },
  'privileged': {
    '': ['clear', 'clock', 'configure', 'copy', 'debug', 'delete', 'disable', 'disconnect', 'erase', 'exit', 'help', 'more', 'no', 'ping', 'reload', 'resume', 'setup', 'show', 'ssh', 'suspend', 'telnet', 'terminal', 'test', 'traceroute', 'undebug', 'write'],
    ...pfx('clear', ['arp-cache', 'counters', 'interface', 'ipv6', 'line', 'mac']),
    'clear ipv6': ['neighbors'],
    'clear mac': ['address-table'],
    ...pfx('clock', ['set']),
    ...pfx('configure', ['terminal']),
    ...pfx('copy', ['flash', 'running-config', 'startup-config', 'tftp']),
    'copy flash': ['startup-config'],
    'copy running-config': ['flash', 'startup-config', 'tftp:'],
    'copy startup-config': ['running-config'],
    'copy tftp': ['running-config'],
    ...pfx('delete', ['flash:vlan.dat', 'nvram']),
    ...pfx('erase', ['nvram', 'startup-config']),
    ...pfx('debug', ['all', 'arp', 'cdp', 'dhcp', 'etherchannel', 'icmp', 'ip', 'ipv6', 'mac', 'packet', 'spanning-tree', 'sw-vlan', 'vlan']),
    'debug ip': ['arp', 'bgp', 'dhcp', 'icmp', 'nat', 'ospf', 'packet', 'route'],
    'debug ip icmp': [],
    'debug ip packet': [],
    'debug ip ospf': ['events', 'hello', 'packet'],
    'debug ip dhcp': ['server'],
    'debug ip arp': [],
    'debug ip bgp': ['events', 'keepalives'],
    'debug ip nat': ['detailed'],
    'debug arp': [],
    'debug cdp': ['packets'],
    'debug vlan': ['packet'],
    'debug sw-vlan': ['packet'],
    'debug spanning-tree': ['events', 'bpdu'],
    ...pfx('show', ['access-lists', 'alias', 'ap', 'archive', 'arp', 'authentication', 'banner', 'boot', 'cdp', 'class-map', 'clock', 'controllers', 'debugging', 'diagnostic', 'dot11', 'environment', 'errdisable', 'etherchannel', 'flash', 'glbp', 'history', 'interface', 'interfaces', 'inventory', 'ip', 'ipv6', 'lldp', 'mac', 'memory', 'mls', 'monitor', 'nameif', 'ntp', 'policy-map', 'port-security', 'processes', 'redundancy', 'route-map', 'running-config', 'sdm', 'sessions', 'snmp', 'spanning-tree', 'ssh', 'standby', 'startup-config', 'storm-control', 'system', 'udld', 'users', 'version', 'vlan', 'vtp', 'wireless', 'wlan']),
    'show ap': ['config', 'join', 'summary'],
    'show ap config': [],
    'show ap join': ['statistics'],
    'show ap join statistics': [],
    'show banner': ['motd'],
    'show cdp': ['neighbors'],
    'show glbp': ['brief'],
    'show route-map': [],
    'show lldp': ['neighbors'],
    'show lldp neighbors': ['detail'],
    'show dot11': ['associations', 'statistics'],
    'show errdisable': ['detect', 'recovery'],
    'show interface': ['trunk'],
    'show interfaces': ['status', 'trunk'],
    'show ip': ['arp', 'bgp', 'cache', 'dhcp', 'eigrp', 'flow', 'interface', 'nat', 'ospf', 'prefix-list', 'protocols', 'route', 'sla', 'source', 'ssh', 'verify'],
    'show ip cache': ['flow'],
    'show ip flow': ['export'],
    'show ip prefix-list': [],
    'show ip sla': ['statistics'],
    'show class-map': ['<name>'],
    'show policy-map': ['interface'],
    'show policy-map interface': ['<interface>'],
    'show ip arp': ['inspection'],
    'show ip bgp': ['summary'],
    'show ip dhcp': ['binding', 'pool', 'snooping'],
    'show ip eigrp': ['neighbors'],
    'show ip interface': ['brief'],
    'show ip nat': ['translations', 'statistics'],
    'show ip ospf': ['database', 'interface', 'neighbor'],
    'show ip source': ['binding'],
    'show ip source binding': ['vlan', 'interface'],
    'show ip verify': ['source'],
    'show ip verify source': [],
    'show ipv6': ['dhcp', 'eigrp', 'interface', 'neighbors', 'ospf', 'prefix-list', 'rip', 'route'],
    'show ipv6 dhcp': ['pool'],
    'show ipv6 eigrp': ['neighbors', 'topology'],
    'show ipv6 prefix-list': [],
    'show ipv6 interface': ['brief'],
    'show ipv6 ospf': [],
    'show ipv6 rip': [],
    'show standby': ['brief'],
    'show mac': ['access-lists', 'address-table'],
    'show mac address-table': ['static'],
    'show mls': ['qos'],
    'show ntp': ['associations', 'status'],
    'show sdm': ['prefer'],
    'show system': ['mtu'],
    'show vlan': ['brief'],
    'show vtp': ['password', 'status'],
    'show wlan': ['summary'],
    'show nameif': [],
    'show ip access-group': [],
    ...pfx('terminal', ['length', 'monitor', 'no', 'width']),
    'terminal no': ['monitor'],
    ...pfx('undebug', ['all']),
    ...pfx('write', ['memory']),
  },
  'config': {
    '': ['access-list', 'alias', 'ap', 'archive', 'banner', 'cdp', 'channel', 'class-map', 'clock', 'crypto', 'default', 'do', 'dot11', 'dot1x', 'enable', 'end', 'errdisable', 'exit', 'hostname', 'interface', 'ip', 'ipv6', 'lldp', 'line', 'mac', 'macro', 'mls', 'monitor', 'no', 'ntp', 'policy-map', 'route-map', 'router', 'same-security-traffic', 'sdm', 'security', 'service', 'snmp-server', 'spanning-tree', 'station-role', 'system', 'template', 'username', 'vlan', 'vtp', 'wlan'],
    ...pfx('route-map', ['<name>']),
    ...pfx('banner', ['exec', 'login', 'motd']),
    ...pfx('cdp', ['holdtime', 'run', 'timer']),
    ...pfx('clock', ['timezone']),
    ...pfx('crypto', ['key']),
    'crypto key': ['generate', 'zeroize'],
    'crypto key generate': ['rsa'],
    'crypto key zeroize': ['rsa'],
    ...pfx('default', ['interface']),
    'ap': [],
    'ap dot11': ['5ghz'],
    'ap dot11 5ghz': ['power-constraint', 'channelswitch'],
    ...pfx('do', ['show']),
    ...pfx('dot11', ['channel', 'mac-filter', 'power', 'ssid', 'station-role']),
    ...pfx('enable', ['password', 'secret']),
    ...pfx('errdisable', ['recovery']),
    'errdisable recovery': ['cause'],
    'interface': ['dot11radio', 'FastEthernet', 'GigabitEthernet', 'Loopback', 'Range', 'Serial', 'Vlan'],
    'interface fastethernet': ['<0-48>', '0/1', '0/2', '0/3', '0/4'],
    'interface gigabitethernet': ['<0-48>', '0/1', '0/2', '1/0/1'],
    'interface vlan': ['<1-4094>'],
    'interface loopback': ['<0-2147483647>'],
    'interface serial': ['0/0/0', '0/1/0'],
    'interface range': ['fastEthernet', 'gigabitEthernet', 'vlan'],

    ...pfx('ip', ['access-list', 'arp', 'default-gateway', 'dhcp', 'domain', 'domain-lookup', 'domain-name', 'flow-export', 'host', 'http', 'name-server', 'nat', 'prefix-list', 'route', 'routing', 'sla', 'ssh']),
    'ip flow-export': ['destination', 'version'],
    'ip flow-export destination': [],
    'ip flow-export version': ['5', '9'],
    'ip prefix-list': [],
    'ip arp': ['inspection'],
    'ip dhcp': ['excluded-address', 'pool', 'snooping'],
    'ip nat': ['inside', 'pool'],
    'ip nat inside': ['source'],
    'ip nat inside source': ['list', 'static'],
    'ip dhcp snooping': ['information', 'vlan'],
    'ip dhcp snooping information': ['option'],
    'ip domain': ['lookup'],
    'ip http': ['server'],
    'ip name-server': [],
    'ip dhcp excluded-address': [],
    'ip nat pool': [],
    'same-security-traffic': [],
    'ip nat inside source list': [],
    'ip nat inside source static': [],
    'ip sla': ['<id>', 'schedule'],
    'ip sla schedule': ['<id>'],
    'ip ssh': ['authentication-retries', 'time-out', 'version'],
    ...pfx('ipv6', ['dhcp', 'prefix-list', 'route', 'router', 'unicast-routing']),
    'ipv6 prefix-list': [],
    'ipv6 dhcp': ['pool'],
    'ipv6 router': ['eigrp', 'ospf', 'rip'],
    'ipv6 router eigrp': [],
    ...pfx('line', ['aux', 'console', 'vty']),
    ...pfx('mac', ['access-list']),
    ...pfx('mls', ['qos']),
    ...pfx('monitor', ['session']),
    ...pfx('no', ['access-list', 'alias', 'banner', 'cdp', 'enable', 'errdisable', 'hostname', 'interface', 'ip', 'ipv6', 'mls', 'monitor', 'router', 'same-security-traffic', 'service', 'spanning-tree', 'username', 'vlan', 'wlan']),
    'no banner': ['exec', 'login', 'motd'],
    'no cdp': ['run'],
    'no enable': ['password', 'secret'],
    'no ip': ['access-list', 'arp', 'default-gateway', 'dhcp', 'domain-lookup', 'host', 'http', 'name-server', 'nat', 'route', 'routing', 'ssh'],
    'no ip arp': ['inspection'],
    'no ip dhcp': ['excluded-address', 'pool', 'snooping'],
    'no ip nat': ['inside', 'pool'],
    'no ip nat inside': ['source'],
    'no ip nat inside source': ['list', 'static'],
    'no ip http': ['server'],
    'no ip ssh': ['time-out'],
    'no ipv6': ['dhcp', 'route', 'router', 'unicast-routing'],
    'no ipv6 dhcp': ['pool'],
    'no ipv6 router': ['eigrp', 'ospf', 'rip'],
    'no mls': ['qos'],
    'no monitor': ['session'],
    'no router': ['bgp', 'eigrp', 'ospf', 'rip'],
    'no same-security-traffic': [],
    'no service': ['password-encryption'],
    'no wlan': ['shutdown'],
    'no wlan shutdown': [],
    ...pfx('ntp', ['server']),
    ...pfx('lldp', ['holdtime', 'reinit', 'run', 'timer', 'tlv-select']),
    'lldp tlv-select': ['all', 'location', 'network-policy', 'power'],
    ...pfx('dot1x', ['system-auth-control']),
    ...pfx('router', ['bgp', 'eigrp', 'ospf', 'rip']),
    ...pfx('sdm', ['prefer']),
    ...pfx('security', ['wep', 'wpa']),
    'security wpa': ['psk'],
    'security wpa psk': ['set-key'],
    'security wpa psk set-key': [],
    'security wep': ['key'],
    'security wep key': ['set-key'],
    'security wep key set-key': [],
    'no security wpa': ['psk'],
    'no security wpa psk': [],
    'no security wep': ['key'],
    'no security wep key': [],
    ...pfx('wlan', ['shutdown']),
    'wlan shutdown': [],
    ...pfx('service', ['password-encryption']),
    ...pfx('snmp-server', ['community', 'contact', 'location']),
    ...pfx('spanning-tree', ['loopguard', 'mode', 'portfast', 'vlan']),
    'spanning-tree loopguard': ['default'],
    'no spanning-tree loopguard': ['default'],
    ...pfx('system', ['mtu']),
    ...pfx('vtp', ['domain', 'mode', 'password']),
  },
  'interface': {
    '': ['bandwidth', 'carrier-delay', 'cdp', 'channel-group', 'channel-protocol', 'delay', 'description', 'do', 'dot1x', 'duplex', 'encapsulation', 'encryption', 'end', 'exit', 'glbp', 'help', 'ip', 'ipv6', 'keepalive', 'lldp', 'load-interval', 'macro', 'mls', 'nameif', 'no', 'power', 'priority-queue', 'queue-set', 'security-level', 'service-policy', 'shutdown', 'spanning-tree', 'speed', 'ssid', 'storm-control', 'switchport', 'tx-queue', 'udld'],
    ...pfx('glbp', ['<group>']),
    'glbp': ['<group>'],
    'glbp <group>': ['ip', 'priority', 'preempt', 'weighting'],
    ...pfx('cdp', ['enable']),
    ...pfx('clock', ['rate']),
    ...pfx('do', ['show']),
    ...pfx('encapsulation', ['dot1q', 'hdlc', 'ppp']),
    ...pfx('ip', ['access-group', 'address', 'arp', 'dhcp', 'directed-broadcast', 'flow', 'helper-address', 'nat', 'proxy-arp', 'verify']),
    'ip flow': ['egress', 'ingress'],
    'ip arp': ['inspection'],
    'ip nat': ['inside', 'outside'],
    'ip arp inspection': ['limit', 'trust'],
    'ip dhcp snooping': ['limit', 'trust'],
    'ip dhcp snooping limit': ['rate'],
    'ip verify': ['source'],
    'dot1x': ['port-control'],
    'dot1x port-control': ['auto', 'force-authorized', 'force-unauthorized'],
    'lldp': ['receive', 'transmit'],
    'service-policy': ['input', 'output'],
    'service-policy input': ['<policy-map>'],
    'service-policy output': ['<policy-map>'],
    ...pfx('ipv6', ['address', 'dhcp', 'eigrp', 'ospf', 'rip']),
    'ipv6 dhcp': ['server'],
    'ipv6 eigrp': ['<as-number>'],
    'ipv6 ospf': ['area'],
    'ipv6 rip': ['enable'],
    ...pfx('mls', ['qos']),
    'mls qos': ['cos', 'trust'],
    'mls qos trust': ['cos', 'dscp', 'ip-precedence'],
    ...pfx('no', ['cdp', 'channel-group', 'description', 'ip', 'ipv6', 'keepalive', 'lldp', 'shutdown', 'spanning-tree', 'standby', 'switchport', 'udld']),
    'no spanning-tree': ['bpduguard', 'cost'],
    ...pfx('ppp', ['authentication', 'pap']),
    'ppp authentication': ['chap', 'pap'],
    'ppp pap': ['sent-username'],
    'no cdp': ['enable'],
    'no ip': ['access-group', 'address', 'arp', 'dhcp', 'directed-broadcast', 'helper-address', 'nat', 'proxy-arp', 'verify'],
    'no ip arp': ['inspection'],
    'no ip arp inspection': ['trust'],
    'no ip dhcp': ['snooping'],
    'no ip dhcp snooping': ['trust'],
    'no ip nat': ['inside', 'outside'],
    'no ip verify': ['source'],
    'no lldp': ['receive', 'transmit'],
    'no ipv6': ['ospf', 'rip'],
    'no ipv6 ospf': ['area'],
    'no ipv6 rip': ['enable'],
    ...pfx('standby', ['ip', 'preempt', 'priority']),
    'no switchport': ['access', 'mode', 'port-security'],
    'no switchport access': ['vlan'],
    ...pfx('power', ['inline']),
    'power inline': ['consumption'],
    ...pfx('priority-queue', ['out']),
    ...pfx('spanning-tree', ['bpduguard', 'cost', 'portfast', 'priority']),
    'spanning-tree bpduguard': ['disable', 'enable'],
    ...pfx('storm-control', ['action']),
    ...pfx('switchport', ['access', 'block', 'mode', 'nonegotiate', 'port-security', 'protected', 'trunk', 'voice']),
    ...pfx('standby', ['ip', 'preempt', 'priority']),
    'switchport access': ['vlan'],
    'switchport port-security': ['aging', 'mac-address', 'maximum', 'violation'],
    'switchport port-security aging': ['time', 'type'],
    'switchport port-security mac-address': ['sticky'],
    'switchport trunk': ['allowed', 'encapsulation', 'native'],
    'switchport trunk allowed': ['vlan'],
    'switchport trunk native': ['vlan'],
    'switchport voice': ['vlan'],
    ...pfx('udld', ['enable', 'port']),
  },
  'config-if-range': {
    '': ['bandwidth', 'carrier-delay', 'cdp', 'channel-group', 'channel-protocol', 'delay', 'description', 'do', 'duplex', 'encapsulation', 'encryption', 'end', 'exit', 'help', 'ip', 'ipv6', 'keepalive', 'lldp', 'load-interval', 'macro', 'mls', 'no', 'power', 'priority-queue', 'queue-set', 'shutdown', 'spanning-tree', 'speed', 'ssid', 'storm-control', 'switchport', 'tx-queue', 'udld'],
    ...pfx('cdp', ['enable']),
    ...pfx('do', ['show']),
    ...pfx('encapsulation', ['dot1q']),
    ...pfx('ip', ['access-group', 'address', 'arp', 'dhcp', 'directed-broadcast', 'helper-address', 'proxy-arp', 'verify']),
    'ip arp': ['inspection'],
    'ip arp inspection': ['limit', 'trust'],
    'ip dhcp': ['snooping'],
    'ip dhcp snooping': ['trust'],
    'ip verify': ['source'],
    'lldp': ['receive', 'transmit'],
    ...pfx('ipv6', ['address', 'dhcp', 'ospf', 'rip']),
    'ipv6 dhcp': ['server'],
    'ipv6 ospf': ['area'],
    'ipv6 rip': ['enable'],
    ...pfx('mls', ['qos']),
    'mls qos': ['cos', 'trust'],
    'mls qos trust': ['cos', 'dscp', 'ip-precedence'],
    ...pfx('no', ['cdp', 'channel-group', 'description', 'ip', 'ipv6', 'keepalive', 'lldp', 'shutdown', 'switchport', 'udld']),
    'no cdp': ['enable'],
    'no ip': ['access-group', 'address', 'arp', 'dhcp', 'directed-broadcast', 'helper-address', 'proxy-arp', 'verify'],
    'no ip arp': ['inspection'],
    'no ip arp inspection': ['trust'],
    'no ip dhcp': ['snooping'],
    'no ip dhcp snooping': ['trust'],
    'no lldp': ['receive', 'transmit'],
    'no ip nat': ['inside', 'outside'],
    'no ip verify': ['source'],
    'no ipv6': ['ospf', 'rip'],
    'no ipv6 ospf': ['area'],
    'no ipv6 rip': ['enable'],
    'no switchport': ['access', 'mode', 'port-security'],
    'no switchport access': ['vlan'],
    ...pfx('power', ['inline']),
    'power inline': ['consumption'],
    ...pfx('priority-queue', ['out']),
    ...pfx('spanning-tree', ['bpduguard', 'cost', 'portfast', 'priority']),
    'spanning-tree bpduguard': ['disable', 'enable'],
    ...pfx('storm-control', ['action']),
    ...pfx('switchport', ['access', 'block', 'mode', 'nonegotiate', 'port-security', 'protected', 'trunk', 'voice']),
    'switchport access': ['vlan'],
    'switchport port-security': ['aging', 'mac-address', 'maximum', 'violation'],
    'switchport port-security aging': ['time', 'type'],
    'switchport port-security mac-address': ['sticky'],
    'switchport trunk': ['allowed', 'encapsulation', 'native'],
    'switchport trunk allowed': ['vlan'],
    'switchport trunk native': ['vlan'],
    'switchport voice': ['vlan'],
    ...pfx('udld', ['enable', 'port']),
  },
  'line': {
    '': ['access-class', 'autocommand', 'do', 'end', 'exec', 'exec-timeout', 'exit', 'help', 'history', 'lockable', 'logging', 'login', 'no', 'password', 'privilege', 'session-limit', 'transport'],
    ...pfx('access-class', []),
    ...pfx('autocommand', []),
    ...pfx('do', ['show']),
    ...pfx('exec', []),
    ...pfx('exec-timeout', []),
    ...pfx('history', ['size']),
    'history size': [],
    ...pfx('lockable', []),
    ...pfx('logging', ['synchronous']),
    ...pfx('login', []),
    ...pfx('no', ['access-class', 'autocommand', 'exec', 'exec-timeout', 'history', 'lockable', 'logging', 'login', 'password', 'session-limit', 'transport']),
    'no logging': ['synchronous'],
    'no transport': ['input'],
    ...pfx('password', []),
    ...pfx('privilege', ['level']),
    'privilege level': [],
    ...pfx('session-limit', []),
    ...pfx('transport', ['input', 'output', 'preferred']),
    'transport input': [],
    'transport output': [],
    'transport preferred': [],
  },
  'vlan': {
    '': ['do', 'end', 'exit', 'help', 'name', 'no', 'state'],
    ...pfx('do', ['show']),
    ...pfx('no', ['name']),
  },
  'dhcp-config': {
    '': ['address', 'default-router', 'dns-server', 'do', 'domain-name', 'end', 'exit', 'lease', 'network', 'no'],
    ...pfx('address', ['prefix']),
    'address prefix': [],
    ...pfx('default-router', []),
    ...pfx('dns-server', []),
    ...pfx('domain-name', []),
    ...pfx('lease', []),
    ...pfx('no', ['address', 'default-router', 'dns-server', 'domain-name', 'network']),
    'no address': ['prefix'],
    'no address prefix': [],
    'no default-router': [],
    'no dns-server': [],
    'no domain-name': [],
    'no network': [],
    ...pfx('do', ['show']),
    ...pfx('network', []),
  },
  'router-config': {
    '': ['aggregate-address', 'area', 'auto-summary', 'bgp', 'default-information', 'do', 'eigrp', 'end', 'exit', 'maximum-paths', 'neighbor', 'network', 'no', 'passive-interface', 'router-id', 'synchronization', 'timers'],
    ...pfx('aggregate-address', []),
    ...pfx('area', ['range', 'stub', 'nssa']),
    'area stub no-summary': [],
    'area nssa no-summary': [],
    'area range': [],
    'area stub': [],
    'area nssa': [],
    ...pfx('auto-summary', []),
    ...pfx('bgp', ['cluster-id', 'graceful-restart', 'router-id']),
    'bgp cluster-id': [],
    'bgp graceful-restart': [],
    'bgp router-id': [],
    ...pfx('default-information', ['always', 'originate']),
    ...pfx('do', ['show']),
    ...pfx('eigrp', ['router-id']),
    'eigrp router-id': [],
    ...pfx('maximum-paths', []),
    ...pfx('neighbor', ['allowas-in', 'as-override', 'default-originate', 'description', 'ebgp-multihop', 'maximum-prefix', 'next-hop-self', 'password', 'remote-as', 'remove-private-as', 'route-map', 'route-reflector-client', 'send-community', 'shutdown', 'soft-reconfiguration', 'timers', 'update-source', 'weight']),
    'neighbor allowas-in': [],
    'neighbor as-override': [],
    'neighbor default-originate': [],
    'neighbor description': [],
    'neighbor ebgp-multihop': [],
    'neighbor maximum-prefix': [],
    'neighbor next-hop-self': [],
    'neighbor password': [],
    'neighbor remote-as': [],
    'neighbor remove-private-as': [],
    'neighbor route-map': [],
    'neighbor route-reflector-client': [],
    'neighbor send-community': [],
    'neighbor shutdown': [],
    'neighbor soft-reconfiguration': [],
    'neighbor timers': [],
    'neighbor update-source': [],
    'neighbor weight': [],
    ...pfx('no', ['aggregate-address', 'auto-summary', 'bgp', 'eigrp', 'maximum-paths', 'neighbor', 'network', 'passive-interface', 'router-id', 'synchronization', 'timers']),
    'no aggregate-address': [],
    'no bgp': ['cluster-id', 'graceful-restart'],
    'no bgp cluster-id': [],
    'no bgp graceful-restart': [],
    'no eigrp': ['router-id'],
    'no eigrp router-id': [],
    'no maximum-paths': [],
    'no neighbor': ['allowas-in', 'as-override', 'default-originate', 'description', 'ebgp-multihop', 'maximum-prefix', 'next-hop-self', 'password', 'remove-private-as', 'remote-as', 'route-reflector-client', 'send-community', 'shutdown', 'soft-reconfiguration', 'timers', 'update-source'],
    'no neighbor allowas-in': [],
    'no neighbor as-override': [],
    'no neighbor default-originate': [],
    'no neighbor description': [],
    'no neighbor ebgp-multihop': [],
    'no neighbor maximum-prefix': [],
    'no neighbor next-hop-self': [],
    'no neighbor password': [],
    'no neighbor remote-as': [],
    'no neighbor remove-private-as': [],
    'no neighbor route-reflector-client': [],
    'no neighbor send-community': [],
    'no neighbor shutdown': [],
    'no neighbor soft-reconfiguration': [],
    'no neighbor timers': [],
    'no neighbor update-source': [],
    'no network': [],
    'no passive-interface': [],
    'no router-id': [],
    'no synchronization': [],
    'no timers bgp': [],
    ...pfx('network', []),
    ...pfx('passive-interface', []),
    ...pfx('router-id', []),
    ...pfx('synchronization', []),
    ...pfx('timers', ['bgp']),
    'timers bgp': [],
  },
  'ssid-config': {
    '': ['authentication', 'guest-mode', 'mbssid', 'wpa-psk'],
    ...pfx('authentication', ['key-management', 'network-eap']),
    'authentication key-management': ['wpa'],
    'authentication key-management wpa': ['version'],
    ...pfx('guest-mode', []),
    ...pfx('mbssid', []),
    ...pfx('no', ['guest-mode', 'mbssid']),
  },
  'dot11-config': {
    '': ['channel', 'encryption', 'mac-filter', 'no', 'power', 'shutdown', 'ssid', 'station-role'],
    ...pfx('channel', []),
    ...pfx('encryption', ['mode']),
    'encryption mode': ['ciphers'],
    ...pfx('mac-filter', []),
    ...pfx('no', ['channel', 'mac-filter', 'shutdown']),
    ...pfx('power', []),
    ...pfx('shutdown', []),
    ...pfx('ssid', []),
    ...pfx('station-role', []),
  },
  'config-std-nacl': {
    '': ['do', 'end', 'exit', 'help', 'no', 'permit', 'deny'],
    ...pfx('do', ['show']),
    ...pfx('no', ['permit', 'deny']),
  },
  'config-ext-nacl': {
    '': ['do', 'end', 'exit', 'help', 'no', 'permit', 'deny'],
    ...pfx('do', ['show']),
    ...pfx('no', ['permit', 'deny']),
  },
};

// Command descriptions for help system
export const commandDescriptions: Record<string, Record<string, string>> = {
  user: {
    'enable': 'Ayrıcalıklı moda geç (Enable privileged mode)',
    'exit': 'Oturumu kapat (Exit session)',
    'show': 'Cihaz bilgilerini göster (Display device information)',
    'ping': 'Ağ bağlantısını test et (Test network connectivity)',
    'telnet': 'Telnet ile uzak cihaza bağlan (Connect to remote device via Telnet)',
    'ssh': 'SSH ile uzak cihaza bağlan (Connect to remote device via SSH)',
    'traceroute': 'Hedef cihaza giden yolu göster (Display route to destination)',
    '?': 'Yardım göster (Display help)',
    'help': 'Yardım göster (Display help)',
  },
  privileged: {
    'configure': 'Yapılandırma moduna gir (Enter configuration mode)',
    'disable': 'Ayrıcalıklı moddan çık (Exit privileged mode)',
    'clock': 'Sistem saatini ayarla (Manage the system clock)',
    'show': 'Cihaz bilgilerini göster (Display device information)',
    'clear': 'Önbelleği temizle (Clear cache/counters)',
    'debug': 'Hata ayıklama etkinleştir (Enable debugging)',
    'undebug': 'Hata ayıklamayı devre dışı bırak (Disable debugging)',
    'all': 'Tüm seçenekler (All debug options)',
    'packet': 'Paket seviyesinde hata ayıklama (Packet level debugging)',
    'icmp': 'ICMP mesajları hata ayıklaması (ICMP debugging)',
    'ospf': 'OSPF protokolü hata ayıklaması (OSPF debugging)',
    'bgp': 'BGP protokolü hata ayıklaması (BGP debugging)',
    'dhcp': 'DHCP işlemleri hata ayıklaması (DHCP debugging)',
    'arp': 'ARP paketleri hata ayıklaması (ARP debugging)',
    'nat': 'NAT dönüştürme hata ayıklaması (NAT debugging)',
    'route': 'Yönlendirme tablosu hata ayıklaması (Routing debugging)',
    'cdp': 'CDP protokolü hata ayıklaması (CDP debugging)',
    'vlan': 'VLAN işlemleri hata ayıklaması (VLAN debugging)',
    'sw-vlan': 'Switch VLAN işlemleri hata ayıklaması (Switch VLAN debugging)',
    'spanning-tree': 'Spanning Tree Protokolü hata ayıklaması (Spanning Tree debugging)',
    'source': 'IP Source Guard ayarları ve bağlama tablosu (IP Source Guard)',
    'binding': 'IP Source Guard bağlama tablosu (IP Source Guard binding table)',
    'verify': 'IP doğrulama ayarları (IP verification)',
    'terminal': 'Terminal ayarlarını yapılandır (Configure terminal settings)',
    'write': 'Yapılandırmayı kaydet (Save configuration)',
    'ping': 'Ağ bağlantısını test et (Test network connectivity)',
    'telnet': 'Telnet ile uzak cihaza bağlan (Connect to remote device via Telnet)',
    'ssh': 'SSH ile uzak cihaza bağlan (Connect to remote device via SSH)',
    'traceroute': 'Hedef cihaza giden yolu göster (Display route to destination)',
    'reload': 'Cihazı yeniden başlat (Reboot device)',
    'exit': 'Oturumu kapat (Exit session)',
    'copy': 'Dosya kopyala (Copy files)',
    'erase': 'Dosya sil (Erase files)',
    'delete': 'Dosya sil (Delete files)',
    'ip': 'IP protokolü ayarları (IP protocol settings)',
    'setup': 'Başlangıç kurulum diyaloğuna gir (Enter initial setup dialog) ⚠️ Stub',
    'test': 'Tanılama testlerini çalıştır (Run diagnostics) ⚠️ Stub',
    'more': 'Dosya veya yapılandırma içeriğini göster; örn. more system:running-config (Display contents of a file or configuration)',
    'disconnect': 'Ağ bağlantısını kes (Disconnect network connection) ⚠️ Stub',
    'resume': 'Askıya alınmış oturuma dön (Resume a suspended session) ⚠️ Stub',
    'suspend': 'Mevcut oturumu askıya al (Suspend current session) ⚠️ Stub',
    '?': 'Yardım göster (Display help)',
    'help': 'Yardım göster (Display help)',
  },
  config: {
    'hostname': 'Cihaz adını ayarla (Set device hostname)',
    'interface': 'Arayüz yapılandırmasına gir (Enter interface configuration)',
    'vlan': 'VLAN yapılandırmasına gir (Enter VLAN configuration)',
    'enable': 'Enable şifresi ayarla (Set enable password)',
    'service': 'Hizmet ayarları (Service settings)',
    'username': 'Kullanıcı adı oluştur (Create username)',
    'line': 'Hat yapılandırmasına gir (Enter line configuration)',
    'banner': 'Başlık mesajı ayarla (Set banner message)',
    'ip': 'IP protokolü ayarları (IP protocol settings)',
    'ipv6': 'IPv6 protokolü ayarları (IPv6 protocol settings)',
    'crypto': 'RSA anahtar yönetimi (RSA key management; IKE/IPsec CLI is not enabled)',
    'snmp-server': 'SNMP community, contact ve location ayarları',
    'ntp': 'NTP ayarları (NTP settings)',
    'clock': 'Saat ayarları (Clock settings)',
    'archive': 'Arşiv ayarları (Archive settings) ⚠️ Stub',
    'alias': 'Komut takma adı oluştur (Create command alias)',
    'macro': 'Makro oluştur (Create macro) ⚠️ Stub',
    'no': 'Komutu iptal et (Negate command)',
    'spanning-tree': 'Spanning Tree ayarları (Spanning Tree settings)',
    'vtp': 'VLAN Trunking Protocol ayarları (VTP settings)',
    'cdp': 'CDP ayarları (CDP settings)',
    'monitor': 'Port izleme (SPAN) ayarları (Configure port monitoring)',
    'class-map': 'QoS sınıf haritası oluştur; örn. class-map match-any VOICE (Create QoS class map)',
    'policy-map': 'QoS politika haritası oluştur; örn. policy-map QOS (Create QoS policy map)',
    'ip sla': 'Sentetik IP SLA tanımla; örn. ip sla 1 icmp-echo 192.0.2.1 (Configure synthetic IP SLA)',
    'lldp': 'LLDP/LLDP-MED ayarları; örn. lldp tlv-select network-policy power (Configure LLDP/LLDP-MED)',
    'dot1x': '802.1X sistem kimlik doğrulamasını etkinleştir (Enable 802.1X system authentication)',
    'template': 'Şablon yapılandırmasına gir (Enter template configuration) ⚠️ Stub',
    'sdm': 'SDM tercihini ayarla (Set SDM preference)',
    'exit': 'Yapılandırma modundan çık (Exit configuration mode)',
    'end': 'Yapılandırma modundan çık (Exit configuration mode)',
    'do': 'Ayrıcalıklı komut çalıştır (Execute privileged command)',
    '?': 'Yardım göster (Display help)',
    'help': 'Yardım göster (Display help)',
  },
  interface: {
    'shutdown': 'Arayüzü kapat (Disable interface)',
    'no': 'Komutu iptal et (Negate command)',
    'speed': 'Bağlantı hızını ayarla (Set connection speed)',
    'duplex': 'Duplex modunu ayarla (Set duplex mode)',
    'description': 'Arayüz açıklaması ekle (Add interface description)',
    'switchport': 'Switch portu ayarları (Switchport settings)',
    'cdp': 'CDP ayarları (CDP settings)',
    'spanning-tree': 'Spanning Tree ayarları (Spanning Tree settings)',
    'channel-group': 'EtherChannel grubu ayarla (Set EtherChannel group)',
    'ip': 'IP protokolü ayarları (IP protocol settings)',
    'ssid': 'Kablosuz ağ adı ayarla (Set wireless network name)',
    'encryption': 'Şifreleme türü ayarla (Set encryption type)',
    'channel': 'Kablosuz kanal ayarla (Set wireless channel)',
    'storm-control': 'Fırtına kontrolü ayarları (Storm control settings)',
    'udld': 'UDLD ayarları (UDLD settings)',
    'monitor': 'Port izleme ayarları (Port monitoring settings)',
    'power': 'PoE güç ayarları; örn. power inline auto/static/never (Configure PoE power settings)',
    'channel-protocol': 'EtherChannel protokolünü seç; örn. channel-protocol lacp/pagp (Set EtherChannel protocol)',
    'priority-queue': 'Öncelikli kuyruk ayarları (paket zamanlaması simülasyon düzeyindedir)',
    'service-policy': 'MQC politikasını interface’e uygula (Apply an MQC policy to an interface)',
    'dot1x': '802.1X port kontrolünü ayarla (Configure 802.1X port control)',
    'lldp': 'LLDP gönderme/alma ayarları (Configure LLDP transmit/receive)',
    'bandwidth': 'Bant genişliğini ayarla (Set bandwidth)',
    'delay': 'Gecikme değerini ayarla (Set delay)',
    'mtu': 'MTU değerini ayarla (Set MTU)',
    'encapsulation': 'Kapsülleme türünü ayarla (Set encapsulation type)',
    'clock': 'Saat hızı ayarları (Clock rate settings)',
    'ppp': 'PPP ayarları (PPP settings)',
    'keepalive': 'Keepalive süresini ayarla (Set keepalive interval)',
    'exit': 'Arayüz yapılandırmasından çık (Exit interface configuration)',
    'end': 'Yapılandırma modundan çık (Exit configuration mode)',
    'do': 'Ayrıcalıklı komut çalıştır (Execute privileged command)',
    '?': 'Yardım göster (Display help)',
    'help': 'Yardım göster (Display help)',
  },
  line: {
    'password': 'Hat şifresi ayarla (Set line password)',
    'login': 'Giriş etkinleştir (Enable login)',
    'no': 'Komutu iptal et (Negate command)',
    'transport': 'Taşıma protokolü ayarla (Set transport protocol)',
    'exec-timeout': 'Oturum zaman aşımı ayarla (Set session timeout)',
    'logging': 'Günlüğe kaydetme ayarları (Logging settings)',
    'history': 'Komut geçmişi ayarları (Command history settings)',
    'privilege': 'Ayrıcalık seviyesi ayarla (Set privilege level)',
    'access-class': 'Erişim kontrol listesini hatta bağla (Apply ACL to line)',
    'session-limit': 'Maksimum oturum sayısını ayarla (Set session limit) ⚠️ Stub',
    'autocommand': 'Otomatik komut ayarla (Set auto-command) ⚠️ Stub',
    'lockable': 'Hat kilitlemeyi etkinleştir (Enable line locking) ⚠️ Stub',
    'exit': 'Hat yapılandırmasından çık (Exit line configuration)',
    'end': 'Yapılandırma modundan çık (Exit configuration mode)',
    'do': 'Ayrıcalıklı komut çalıştır (Execute privileged command)',
    '?': 'Yardım göster (Display help)',
    'help': 'Yardım göster (Display help)',
  },
  vlan: {
    'name': 'VLAN adı ayarla (Set VLAN name)',
    'state': 'VLAN durumunu ayarla (Set VLAN state)',
    'no': 'Komutu iptal et (Negate command)',
    'debug': 'Hata ayıklama etkinleştir (Enable debugging)',
    'undebug': 'Hata ayıklamayı devre dışı bırak (Disable debugging)',
    'exit': 'VLAN yapılandırmasından çık (Exit VLAN configuration)',
    'end': 'Yapılandırma modundan çık (Exit configuration mode)',
    'do': 'Ayrıcalıklı komut çalıştır (Execute privileged command)',
    '?': 'Yardım göster (Display help)',
    'help': 'Yardım göster (Display help)',
  },
  'router-config': {
    'network': 'Ağ tanımla (Define network)',
    'router-id': 'Router kimliği ayarla (Set router ID)',
    'passive-interface': 'Pasif arayüz ayarla (Set passive interface)',
    'default-information': 'Varsayılan rota bilgisi (Default route information)',
    'neighbor': 'BGP komşusu yapılandır (Configure BGP neighbor)',
    'no': 'Komutu iptal et (Negate command)',
    'debug': 'Hata ayıklama etkinleştir (Enable debugging)',
    'undebug': 'Hata ayıklamayı devre dışı bırak (Disable debugging)',
    'exit': 'Router yapılandırmasından çık (Exit router configuration)',
    'end': 'Yapılandırma modundan çık (Exit configuration mode)',
    'do': 'Ayrıcalıklı komut çalıştır (Execute privileged command)',
    '?': 'Yardım göster (Display help)',
    'help': 'Yardım göster (Display help)',
  },
  'dhcp-config': {
    'network': 'DHCP ağı tanımla (Define DHCP network)',
    'address': 'IP adresi aralığı (IP address range)',
    'default-router': 'Varsayılan ağ geçidi (Default gateway)',
    'dns-server': 'DNS sunucusu (DNS server)',
    'lease': 'Kira süresi (Lease duration)',
    'domain-name': 'Alan adı (Domain name)',
    'no': 'Komutu iptal et (Negate command)',
    'debug': 'Hata ayıklama etkinleştir (Enable debugging)',
    'undebug': 'Hata ayıklamayı devre dışı bırak (Disable debugging)',
    'exit': 'DHCP yapılandırmasından çık (Exit DHCP configuration)',
    'end': 'Yapılandırma modundan çık (Exit configuration mode)',
    'do': 'Ayrıcalıklı komut çalıştır (Execute privileged command)',
    '?': 'Yardım göster (Display help)',
    'help': 'Yardım göster (Display help)',
  },
};
